src/components/atoms/input.tsx
src/components/organisms/triggers/add.tsx
src/components/organisms/triggers/edit.tsx
src/components/organisms/triggers/formParts/webhook.tsx

1. Moved the webhook URL field to the end of the "Add new trigger" form
2. Highlighted the Webhook URL field after trigger creation
https://linear.app/autokitteh/issue/UI-754/triggers-add-form-move-webhook-url-to-the-bottom …

refactor: move webhook url in triggers to the end of the form

---

src/components/organisms/deployments/sessions/table.tsx
src/hooks/useVirtualizedList.tsx
src/store/cache/useOutputsCacheStore.ts

At this moment after we loaded the logs (outputs/activities) for the first time, when we approach next time to the same session, it won't reload, and we will need to reload it manually.
The desired: every time we click a session row in the table, the logs would reload.
https://linear.app/autokitteh/issue/UI-773/load-logs-each-time-we-enter-the-session
-   [ ] 🎨 (style) - …

fix: load logs each time we enter the session

---

package-lock.json
package.json

Fix following error in all latest github actions runs:
`error while loading shared libraries: libicudata.so.74: cannot open shared object file: No such file or directory`
https://linear.app/autokitteh/issue/UI-782/fix-e2e-tests-in-ci
-   [x] ⚙️ …

ci: upgrade playwright to fix e2e tests

---

src/components/organisms/connections/integrations/googleforms/add.tsx
src/components/organisms/connections/integrations/integrationEditForm.tsx
src/hooks/useConnectionForm.ts

1. User creates a Google Calendar/Forms connection and specifies a calendar/form ID
2. User edits the connection
Expected: the previously-specified ID should be displayed in the ID field
Actual: the ID field is always empty when editing an existing connection, even if an ID was specified originally
https://linear.app/autokitteh/issue/UI-734/show-previous-calendar-and-form-ids-when-editing-google-connections
-   [ ] 📄 (test) - Tests - Adding missing …

fix: display form and cal and json in google connection forms

---

src/components/organisms/deployments/sessions/tabs/activities/infiniteList.tsx
src/components/organisms/deployments/sessions/tabs/activities/infiniteRow.tsx

In almost every function long enough, it will take 2 rows on a smaller screen sizes, this screenshot is from 1440*900px resolution:
https://linear.app/autokitteh/issue/UI-742/increase-the-height-of-a-row-in-the-activity-log …

fix: enlarge row height when the window is smaller

---

src/components/organisms/deployments/sessions/viewer.tsx
src/locales/en/deployments/translation.json
src/locales/en/services/translation.json
src/models/event.model.ts
src/services/sessions.service.ts

1. Hide fields if there is no content - no event ID or no source (if we are running the session manually)
2. Divide and display the source (webhook/scheduler/connection) and its name separated
3. Don't log an error when the session has no event.
https://linear.app/autokitteh/issue/UI-781/improve-session-information-for-session-viewer
-   [ ] 🎨 (style) - Styles - Changes that …

refactor: improve session information for session-viewer

---

src/hooks/useConnectionForm.ts

Connection edited successfully - error message displayed instead of success
https://linear.app/autokitteh/issue/UI-777/connection-edited-successfully-error-message-displayed-instead-of …

fix: display success message when connection successfully edited, not error

---

src/components/pages/project.tsx

Fix following error: [Link](https://autokitteh.sentry.io/issues/5993673961/?project=4508127205982208&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1)
Caused by missing `return` in the `if` statement:
https://linear.app/autokitteh/issue/UI-799/fix-cannot-read-project-name-on-project-load
-   [ ] 🎨 (style) - …

fix: fix 'cannot read project name' on project load

---

src/components/organisms/deployments/sessions/tabs/outputs.tsx

Shouldn't trims whitespaces in session log:
Here's an example of a single print from a workflow, which contains an indented JSON block with multiple lines:
And here's how it looks in the web UI's session log:
All the spaces in the beginning of lines within the log message are trimmed - but they shouldn't be.
After the fix:
https://linear.app/autokitteh/issue/UI-793/shouldnt-trims-whitespaces-in-session-log
-   [ ] 📄 (test) - Tests - Adding missing …

fix: display whitespaces in session log prints

---

src/locales/en/projects/translation.json

Fix the info message for a successful project build - {{buildId}} instead of {{error}}:
https://github.com/user-attachments/assets/4563adb9-2687-41b1-997f-c859231da599
https://linear.app/autokitteh/issue/UI-795/project-build-error
-   [ ] ⚙️ (ci) …

fix: change project build info message

---

src/constants/lists/connections/options.constants.ts
src/utilities/index.ts
src/utilities/sortIntegrationsMap.utils.ts

[Sort integrations when selecting for a new connection](https://linear.app/autokitteh/issue/UI-692/sort-integrations-when-selecting-for-a-new-connection): The list needs to be sorted alphanumerically by the display name of the integrations
https://linear.app/autokitteh/issue/UI-692/sort-integrations-when-selecting-for-a-new-connection
-   [ ] 🎨 (style) - Styles - Changes that …

fix: sort integrations in add or edit connection page

---

src/components/organisms/connections/integrations/googleGemini/edit.tsx

[Missing line break in Google Gemini info links](https://linear.app/autokitteh/issue/UI-701/missing-n-in-google-gemini-info-links)
https://linear.app/autokitteh/issue/UI-701/missing-n-in-google-gemini-info-links …

fix: divide info link for gemini connection into two lines

---

src/components/organisms/deployments/sessions/tableRow.tsx
src/components/organisms/deployments/sessions/viewer.tsx
src/components/organisms/deployments/tableContent.tsx
src/components/organisms/editorTabs.tsx
src/constants/global.constants.ts
src/constants/index.ts
src/models/sessionLogRecord.model.ts
src/services/logger.service.ts

**Sessions table on the left:**
"Start time" is in UTC, should be local time like everywhere else
**Session log on the right:**
Date at the top: "mm.dd.yy" is a valid choice, but common only in the US. A much better one is what you already use in the left sessions table: "yyyy-mm-dd"
Time at the top: specify seconds (":ss") like everywhere else, not just "hh:mm"
https://linear.app/autokitteh/issue/UI-789/inconsistent-time-in-session-page
-   [ ] 📄 …

fix: align local time and date formats

---

src/components/organisms/connections/integrations/github/authMethods/pat.tsx

Should be: `{apiBaseUrl}/github/webhook/{webhookKey}`
Instead of: `{apiBaseUrl}/{webhookKey}`
https://linear.app/autokitteh/issue/UI-813/add-missing-url-path-in-github-pat-connection-configuration …

fix: add missing url path in github pat connection configuration

---

src/components/organisms/connections/integrations/github/authMethods/pat.tsx

The webhook URL is not updated when creating a new connection (active only on edit)
https://linear.app/autokitteh/issue/UI-813/add-missing-url-path-in-github-pat-connection-configuration
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our …

fix: add missing url path in github pat for new connection configuration

---

src/models/activity.model.ts

When activity results in an error, UI still display a green "completed"
in this case there was an error, looking at the session log record you can see it:
https://linear.app/autokitteh/issue/UI-776/when-activity-results-in-an-error-ui-still-display-a-green-completed
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, …

fix: activity display completed instead of error

---

src/components/organisms/connections/integrations/confluence/authMethods/oauth.tsx
src/components/organisms/connections/integrations/jira/authMethods/oauth.tsx
src/locales/en/integrations/translation.json

[Update "more information" links for all integrations and all auth types:](https://linear.app/autokitteh/issue/UI-699/update-more-information-links-for-all-integrations-and-all-auth-types) Also, various (but not all) OAuth connection types include a message between the "More Information" links and the "Start OAuth Flow" button - get rid of these messages.
https://linear.app/autokitteh/issue/UI-699/update-more-information-links-for-all-integrations-and-all-auth-types
-   [ ] 📄 (docs) - Documentation - …

fix: remove redundant info from atlassian and jira oauth forms 

---

src/components/organisms/connections/integrations/asana/add.tsx
src/components/organisms/connections/integrations/asana/edit.tsx
src/components/organisms/connections/integrations/confluence/authMethods/apiToken.tsx
src/components/organisms/connections/integrations/discord/add.tsx
src/components/organisms/connections/integrations/discord/edit.tsx
src/components/organisms/connections/integrations/github/authMethods/oauth.tsx
src/components/organisms/connections/integrations/github/authMethods/pat.tsx
src/components/organisms/connections/integrations/google/authMethods/jsonKey.tsx
src/components/organisms/connections/integrations/google/authMethods/oauth.tsx
src/components/organisms/connections/integrations/googleGemini/add.tsx
src/components/organisms/connections/integrations/googleGemini/edit.tsx
src/components/organisms/connections/integrations/googlecalendar/authMethods/jsonKey.tsx
src/components/organisms/connections/integrations/googlecalendar/authMethods/oauth.tsx
src/components/organisms/connections/integrations/googleforms/authMethods/jsonKey.tsx
src/components/organisms/connections/integrations/googleforms/authMethods/oauth.tsx
src/components/organisms/connections/integrations/jira/authMethods/apiToken.tsx
src/components/organisms/connections/integrations/openAI/add.tsx
src/components/organisms/connections/integrations/openAI/edit.tsx
src/components/organisms/connections/integrations/slack/authMethods/oauth.tsx
src/components/organisms/connections/integrations/slack/authMethods/socket.tsx
src/components/organisms/connections/integrations/twilio/authMethods/apiKey.tsx
src/components/organisms/connections/integrations/twilio/authMethods/authToken.tsx

For OAuth-based connections, this appears above the "Start OAuth Flow" button, but for non-OAuth-based connections it appears below.
Move all "+ More Information" links for all connection types above the button, nothing should be below it anyway - users need to understand that they are useful before clicking the button.
https://linear.app/autokitteh/issue/UI-791/inconsistent-location-of-more-information-in-connection-pages
-   [ ] 📄 (test) - Tests - …

refactor: move all 'more information' links above the 'save' button in connections forms

---

src/components/organisms/deployments/sessions/tabs/outputs.tsx

Long logs displayed only until the end of the screen, even if the line is long:
After the fix:
https://linear.app/autokitteh/issue/UI-873/multiline-logs-not-displayed-correctly …

fix: display multiline logs in session viewer

---

src/components/organisms/deployments/sessions/viewer.tsx

1. Remove the source
2. In case of connection, display the connection name and no connection
3. Keep the label Source, remove the label Source Type
https://linear.app/autokitteh/issue/UI-863/session-view-trigger-source-and-trigger-type
-   [ ] ⚙️ …

refactor: remove duplicated field (source) from session viewer

---

src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
src/store/useManualRunStore.ts

Save the manual run configuration state when we move between deployments and when the user changes the file of the manual run.
https://linear.app/autokitteh/issue/UI-871/the-run-paramters-should-be-saved-between-deployments-so-the-user
-   [ ] ⚙️ …

refactor: save manual run configuration state when we move between deployments

---

src/components/organisms/deployments/sessions/tabs/activities/infiniteList.tsx
src/components/organisms/deployments/sessions/tabs/outputs.tsx
src/components/organisms/deployments/sessions/viewer.tsx
src/hooks/useVirtualizedList.tsx
src/interfaces/hooks/useVirtualizedList.interface.ts
src/interfaces/store/activitiesAndOutputsCache.store.interface.ts
src/store/cache/useActivitiesCacheStore.ts
src/store/cache/useOutputsCacheStore.ts

https://linear.app/autokitteh/issue/UI-854/session-viewer-on-refresh-change-only-status-end-time-duration-logs …

fix: prevent loader display in viewer session

---

src/components/organisms/deployments/sessions/viewer.tsx

Session outputs loader displayed after the logs are loaded
https://linear.app/autokitteh/issue/UI-883/session-outputs-loader-displayed-after-the-logs-are-loaded …

fix: don't show loader in session outputs when loading ended

---

src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
src/constants/namespaces.logger.constants.ts
src/locales/en/errors/translation.json
src/models/activity.model.ts

Display correct return value in session viewer - Display a proper JSON instead of the current string.
Currently, the returned values per session activity are not readable, here is an example:
```
Y2NvcHlfcmVnCl9yZWNvbnN0cnVjdG9yCnAwCihjcmVxdWVzdHMubW9kZWxzClJlc3BvbnNlCnAxCmNfX2J1aWx0aW5fXwpvYmplY3QKcDIKTnRwMwpScDQKKGRwNQpWX2NvbnRlbnQKcDYKY19jb2RlY3MKZW5jb2RlCnA3CihWe1x1MDAwYSAgImFyZ3MiOiB7XHUwMDBhICAgICJpIjogIjI2IiwgXHUwMDBhICAgICJtZXNzYWdlIjogImhlbGxvIiwgXHUwMDBhICAgICJuYW1lIjogIndvcmxkIiwgXHUwMDBhICAgICJ4IjogIjUyIiwgXHUwMDBhICAgICJ5IjogIjAiXHUwMDBhICB9LCBcdTAwMGEgICJoZWFkZXJzIjoge1x1MDAwYSAgICAiQWNjZXB0IjogIiovKiIsIFx1MDAwYSAgICAiQWNjZXB0LUVuY29kaW5nIjogImd6aXAsIGRlZmxhdGUiLCBcdTAwMGEgICAgIkhvc3QiOiAiaHR0cGJpbi5vcmciLCBcdTAwMGEgICAgIlVzZXItQWdlbnQiOiAicHl0aG9uLXJlcXVlc3RzLzIuMzIuMyIsIFx1 …
```

fix: display correct return value in activity viewer per session

---

src/components/organisms/deployments/table.tsx
src/components/organisms/topbar/project/buttons.tsx
src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
src/components/pages/project.tsx
src/interfaces/models/index.ts
src/interfaces/models/session.interface.ts
src/interfaces/store/manualRunStore.interface.ts
src/locales/en/deployments/translation.json
src/locales/en/validations/translation.json
src/store/useManualRunStore.ts
src/types/models/buildInfoRuntimes.type.ts
src/utilities/convertBuildRuntimesToViewTriggers.utils.ts
src/validations/manualRun.schema.ts

**Single-shot and triggers missing entry-point function names in buildInfo runtimes exports**
Instead of clear text - display a dropdown with all functions coming from the build info (BuildService.Describe function).
https://linear.app/autokitteh/issue/UI-956/manual-run-add-the-ability-to-select-function-out-of-a-dropdown
-   [ ] 🎨 (style) - Styles - Changes that do not affect …

feat(UI-956): functions select in manual run

---

e2e/pages/dashboard.ts
src/components/molecules/menu/menu.tsx
src/components/organisms/dashboard/projectsTable.tsx
src/components/organisms/index.ts
src/components/organisms/newProjectModal.tsx
src/components/organisms/sidebar/sidebar.tsx
src/components/organisms/topbar/dashboard.tsx
src/enums/components/modal.enum.ts
src/interfaces/store/projectStore.interface.ts
src/locales/en/modals/translation.json
src/services/projects.service.ts
src/store/useProjectStore.ts

When we click on Plus (new project), instead of creating a project with a random name - display a modal like we have with the templates - to get the new project name.
If a project with that name exist - display an error.
https://linear.app/autokitteh/issue/UI-949/create-new-project-open-creation-modal-like-in-templates
-   [ ] 🎨 (style) - Styles - Changes that do not affect …

feat(UI-952): create new project - open creation modal like in templates

---

src/components/organisms/triggers/table/popoverContent.tsx
src/interfaces/store/cacheStore.interface.ts
src/services/integrations.service.ts
src/store/cache/useCacheStore.ts
src/types/components/tables/index.ts
src/types/components/tables/triggersTable.type.ts

In some of the connections we are missing an icon here:
https://linear.app/autokitteh/issue/UI-975/fix-missing-connection-icon-in-trigger-popover …

fix(UI-975): bring back missing icon of a connection in the trigger popover

---

src/store/useManualRunStore.ts
src/utilities/convertBuildRuntimesToViewTriggers.utils.ts

When we try to run `convertBuildRuntimesToViewTriggers` function and the deployed version has broken files, we shouldn't write to system log, and need simply to display an empty list of functions.
https://github.com/user-attachments/assets/6092b4bb-f641-4fb1-96f2-7fa90df344e0
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, …

fix(UI-1001): fix convert runtimes to files and function when the object is invalid

---

src/components/organisms/triggers/edit.tsx
src/hooks/useConnectionForm.ts

When there is an issue saving connection - we should display a toast with an error:
https://github.com/user-attachments/assets/81c2f4c4-2a80-4209-b680-a686e6dc1e58
https://linear.app/autokitteh/issue/UI-1008/when-there-is-an-error-in-save-connection-no-toast-displayed
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, …

fix(1008): improve error handling in connection editing and remove redundant toast notification

---

src/components/molecules/menu/menu.tsx
src/components/pages/dashboard.tsx
src/constants/namespaces.logger.constants.ts
src/locales/en/menu/translation.json
src/store/useProjectStore.ts

Avoid situation where everything looks okay, but actually we can't fetch projects from the backend.
https://linear.app/autokitteh/issue/UI-1015/display-an-error-in-case-the-app-cant-fetch-projects …

fix(UI-1015): display error when projects cant load in menu

---

src/components/organisms/topbar/project/navigation.tsx

https://linear.app/autokitteh/issue/UI-1030/fix-default-path-for-assets-tab-to-code
-   [ ] ☑️ …

fix(UI-1030): update default path for assets tab to '/code'

---

src/utilities/convertWrappedJson.utils.ts

When our converter tries to convert a string using `JSON.parse` obviously it will get an exception, added type check, in case we get a string - save the value as is, in case `JSON.parse` doesn't fail - meaning the value is a valid JSON, meaning this is the value we should keep in `result[key]`.
Example of the bug:
https://linear.app/autokitteh/issue/UI-1000/event-issues
-   [ …

fix(UI-1000): fix nested json converter when string

---

src/utilities/copyToClipboard.utils.ts

Currently, we display a success message with an error text:
We should display an error toast with the same message.
https://linear.app/autokitteh/issue/UI-1029/display-an-error-message-on-copy-fail …

fix(UI-1029): display an error message when copy button fails

---

src/components/molecules/menu/menu.tsx
src/components/molecules/popover/popoverListContent.tsx
src/components/organisms/sidebar/sidebar.tsx
src/hooks/usePopover.ts
src/interfaces/components/popover.interface.ts

**Projects sub-menu in the sidebar - Buttons design got wrong**
**Profile button in the sidebar**
1. The animation is wrong - it shouldn't come from the left
2. Should open on the right, not on top
3. Should open on click, not on hover
https://github.com/user-attachments/assets/a7a5e92c-9e99-47e5-a85c-64a3f6fc8b7e
-   [ ] 🎨 (style) - Styles - Changes that do not affect the …

fix(UI-1035): popover bugs on sidebar

---

src/components/organisms/events/table/header.tsx
src/components/organisms/events/table/row.tsx

Events - make type column wider and IDs shorter
Before (type column had a little space):
After (more space for the type column):
https://linear.app/autokitteh/issue/UI-1037/events-make-type-column-wider-and-ids-shorter …

fix(UI-1037): events table - make the columns equal width

---

src/components/organisms/triggers/table.tsx

Display trigger info popover on hover instead of on click
https://linear.app/autokitteh/issue/UI-1039/display-trigger-info-popover-on-hover-instead-of-on-click …

fix(UI-1039): display trigger info popover on hover instead of on click

---

src/components/organisms/triggers/table.tsx

Fix Misalignment of “Call” Column in Triggers Table
Before:
After:
After name column fix:
https://linear.app/autokitteh/issue/UI-1014/fix-misalignment-of-type-and-call-columns-in-triggers-table
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes …

fix(UI-1014): fix trigger table alignment

---

src/components/organisms/connections/edit.tsx
src/components/organisms/connections/integrations/integrationEditForm.tsx
src/hooks/index.ts
src/hooks/useEvent.ts

**Display loader while connection information is loaded**
When we enter the Edit Connection page, display a loader on the left side until the information is completely loaded - to avoid the user seeing the connection fields loading one by one, he should see a complete connection after all data is loaded:
https://github.com/user-attachments/assets/5eb27188-36e9-431a-ab43-b849125ede8f
https://linear.app/autokitteh/issue/UI-1009/while-connection-information-is-loaded-display-a-loader
-   [ ] 📄 (docs) - Documentation …

feat(UI-1009): display loader while connection information loaded

---

src/components/organisms/connections/edit.tsx
src/components/organisms/connections/integrations/integrationEditForm.tsx

When we edit the connection, the loader won't switch to the connection details while it should:
https://linear.app/autokitteh/issue/UI-1072/loader-on-connection-edit-displayed-constantly
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our …

fix(UI-1072): fix loader display on connection edit

---

src/components/organisms/events/table/row.tsx

Events table - add ID tooltip on hover, since the full ID isn't displayed:
https://linear.app/autokitteh/issue/UI-1067/events-table-add-id-tooltip-on-hover …

feat(UI-1067): add full text tooltip in events table cells on hover

---

src/components/organisms/deployments/sessions/viewer.tsx
src/components/organisms/deployments/tableContent.tsx
src/components/organisms/topbar/project/navigation.tsx
src/components/pages/project.tsx
src/hooks/index.ts
src/hooks/useLastVisitedEntity.ts
src/interfaces/store/projectStore.interface.ts
src/store/useProjectStore.ts

When we move between project assets to deployments to sessions, when we visit sessions of a specific deployment, when we get to assets/deployments and then click back on sessions, we should get the same deployment we visited last time.
https://linear.app/autokitteh/issue/UI-1016/remember-last-deployment-we-displayed
-   [ ] 🎨 (style) - Styles - Changes that do not affect the …

fix(UI-1016): remember last visited deployment and session

---

src/components/molecules/idCopyButton.tsx
src/components/organisms/events/table/header.tsx
src/components/organisms/events/table/row.tsx

Events table - change column width back to percent - In order to avoid states like this:
After:
2K:
1920px:
1440px:
https://linear.app/autokitteh/issue/UI-1099/events-table-change-column-width-back-to-percents …

fix(UI-1099): events table - change column width back relative to resolution

---

src/components/molecules/idCopyButton.tsx

It is not useful to display just a few letters from the ID, which are the same for all entities anyway. 
Display the prefix, and the last three characters instead.
https://linear.app/autokitteh/issue/UI-1050/events-page-badly-truncated-columns
- …

feat(UI-1050): id copy button breakdown to suffix and prefix

---

src/components/organisms/connections/table.tsx
src/components/organisms/triggers/table.tsx

Triggers: the type is not aligned with the information icon:
In connections, the App column isn't truncated properly:
https://linear.app/autokitteh/issue/UI-1114/align-triggers-and-connections-tables …

fix(UI-1114): align triggers and connections tables

---

src/components/atoms/table/tD.tsx
src/components/organisms/triggers/table.tsx

Triggers - Move the information icon with popper to the actions columns
https://linear.app/autokitteh/issue/UI-1115/triggers-move-the-information-icon-with-popper-to-the-actions-columns …

refactor(UI-1115): move the info icon to the actions column in triggers table

---

src/components/organisms/topbar/project/manualRun/manualRunButtons.tsx

Manual Run - Allow manual runs when moving between projects
The bug was that the start manual run function wasn't updating when we moved between project, since the projectId wasn't in the `useCallback` dependencies.
https://linear.app/autokitteh/issue/UI-1119/manual-run-allow-manual-runs-when-moving-between-projects
-   [ ] 🎨 (style) - Styles - Changes that do not affect the …

fix(UI-1119): manual run activate previous project

---

src/components/atoms/checkbox.tsx
src/components/organisms/editorTabs.tsx
src/components/organisms/settings/profile/profile.tsx
src/interfaces/components/checkbox.interface.ts
src/locales/en/settings/translation.json

Autosave - Move the definition to user setting, save the definition in cookies, and display only the selected variant - autosave or manual save.
https://linear.app/autokitteh/issue/UI-840/autosave-move-the-definition-to-user-setting
-   [ ] ⚙️ …

feat(UI-840): setup is autosave in user settings

---

src/components/atoms/buttons/button.tsx
src/components/molecules/copyButton.tsx
src/components/molecules/idCopyButton.tsx
src/components/organisms/connections/table.tsx
src/locales/en/tabs/translation.json

Display Connection ID in the connections table as an information popover:
https://linear.app/autokitteh/issue/UI-1068/connections-table-add-connection-id-column …

feat(UI-1068): add connection id in popover in connections table

---

src/components/organisms/dashboard/templates/tabs/createModal.tsx
src/components/organisms/editorTabs.tsx
src/hooks/useCreateProjectFromTemplate.tsx
src/hooks/useFileOperations.ts
src/interfaces/store/cacheStore.interface.ts
src/interfaces/store/templates.interface.ts
src/locales/en/dashboard/translation.json
src/services/indexedDb.service.ts
src/services/templatesIndexedDb.service.ts
src/store/cache/useCacheStore.ts
src/store/useTemplatesStore.ts

Currently we keep only 1 project files in IndexedDB, but if we work with more than 1 window, we have to keep all files for all opened projects.
https://linear.app/autokitteh/issue/UI-1118/enable-to-work-with-multiple-windows-on-multiple-projects
- …

fix(UI-1118): enable working on multiple projects in different windows

---

src/hooks/useCreateProjectFromTemplate.tsx

When we click on quickstart in the welcome page, we get an error.
https://linear.app/autokitteh/issue/UI-1123/fix-project-creation-on-quickstart-click …

fix(UI-1123): fix quickstart creation on intro page

---

src/store/useProjectStore.ts

Optimize projects table to fetch deployments per project only once instead of twice
https://linear.app/autokitteh/issue/UI-1132/optimize-projects-table-to-fetch-deployments-per-project-only-once
-   [x] 🏎 (perf) - Optimization
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes …

perf(UI-1132): load deployments in projects table once instead of twice

---

src/components/organisms/deployments/tableContent.tsx
src/components/organisms/topbar/project/buttons.tsx
src/components/organisms/topbar/project/manualRun/manualRunButtons.tsx
src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
src/interfaces/store/manualRunStore.interface.ts
src/locales/en/deployments/translation.json
src/store/useManualRunStore.ts

Bug - Start session always run on the last deployment
https://github.com/user-attachments/assets/74da5608-6981-4749-bb16-a78bd2d67bad
https://linear.app/autokitteh/issue/UI-1133/bug-start-session-always-run-on-the-last-deployment …

fix(UI-1133): manual run config on deployments change

---

src/components/organisms/deployments/sessionStats.tsx

https://linear.app/autokitteh/issue/UI-1139/sessions-in-created-status-arent-displayed-in-the-deployments-table …

fix(UI-1139): display sessions in created status in deployments table

---

src/components/organisms/connections/table.tsx
src/components/organisms/triggers/table/popoverContent.tsx
src/types/components/tables/triggersTable.type.ts

Change the connection ID in the trigger info popover to idCopyButton
https://linear.app/autokitteh/issue/UI-1125/change-the-connection-id-in-the-trigger-info-popover-to-idcopybutton

refactor(UI-1125): simplify IdCopyButton usage in ConnectionsTable component

---

src/components/molecules/modal.tsx

Modals - focus on approval button when modal is opened & implement focus trap
https://linear.app/autokitteh/issue/UI-1147/modals-focus-on-approval-button-when-modal-is-opened-and-implement

feat(UI-1147): focus trap in modals

---

src/components/organisms/dashboard/templates/section.tsx

Make the icon 85% smaller
https://linear.app/autokitteh/issue/UI-1175/reduce-templates-icon-085percent

fix(UI-1175): adjust icon size in ProjectTemplatesSection

---

src/components/organisms/deployments/sessions/viewer.tsx
src/components/organisms/events/viewer.tsx

viewers (events, sessions) - remove Close (X)
https://linear.app/autokitteh/issue/UI-1174/viewers-events-sessions-remove-close-x

refactor(UI-1174): remove close icon session and event viewer component

---

src/components/organisms/deployments/sessions/viewer.tsx
src/components/organisms/events/viewer.tsx

When there is a problem fetching an event, you should reset and display an error instead the viewer.
https://linear.app/autokitteh/issue/UI-1173/events-sessions-when-there-is-an-error-reset-the-viewer-and-close-it

fix(UI-1173): close editor/viewer on fetch error in session and event viewers

---

src/services/users.service.ts
src/store/useOrganizationStore.ts

Don't show error toast when getUser not finding the user
https://linear.app/autokitteh/issue/UI-1202/dont-show-error-toast-when-getuser-not-finding-user

fix(UI-1202): when we invite user, we shouldnt display error if he is not exist

---

src/app.tsx
src/components/organisms/settings/user/organizations/table.tsx
src/components/organisms/sidebar/userMenu.tsx

Move add organization page under myOrganizations in userSettings
https://linear.app/autokitteh/issue/UI-1209/move-add-organization-page-under-myorganizations-in-usersettings

fix(UI-1209): move add organization page to user settings

---

src/components/templates/settingsLayout.tsx

Bug: settings title not changing when we move from organizations to user settings
https://linear.app/autokitteh/issue/UI-1227/bug-settings-title-not-changing-when-we-move-from-organizations-to

fix(UI-1227): fix settings title display when we move between organizations and users

---

src/components/organisms/settings/organization/members/createMemberModal.tsx

Display loader on Create click
https://linear.app/autokitteh/issue/UI-1228/create-member-display-loader-on-create-click

feat(UI-1228): add loader during member creation process

---

src/components/organisms/systemLog.tsx
src/components/organisms/variables/table.tsx

When variable value is very long, the screen is too large
https://linear.app/autokitteh/issue/UI-1210/when-variable-value-is-very-long-the-screen-is-too-large

fix(UI-1210): limit maximum width of table cell in variable value

---

src/components/organisms/sidebar/sidebar.tsx
src/components/organisms/sidebar/userMenu.tsx
src/constants/featureFlags.constants.ts
src/vite-env.d.ts
vite.config.ts

Remove enableNewOrgsAndUsersDesign
https://linear.app/autokitteh/issue/UI-1151/when-enableneworgsandusersdesign-feature-flag-removed-move-feedback

refactor(UI-1151): remove unused feature flags and clean up user menu

---

src/components/organisms/deployments/sessions/viewer.tsx

Fix execution Flow tab in the session viewer not marked as chosen, but the outputs tab is marked instead.
https://linear.app/autokitteh/issue/UI-1196/execution-flow-tab-in-sessions-doesnt-marked-as-active

fix(UI-1196): adjust active tab in sessions page

---

src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
src/store/useManualRunStore.ts

Don't reset the manual run configuration on Deploy
https://linear.app/autokitteh/issue/UI-1258/dont-reset-manual-run-configuration-on-deploy

fix(UI-1258): save the manual run configuration on deploy action

---

src/components/pages/dashboard.tsx
src/components/pages/intro.tsx

When we log in (we can see that on staging/production where the loading is slower), the projects table homepage "jumps" from 70% height to 100%.
Also, when we filter templates category to a category with a small number of templates 1-4 on large screens, the homepage height becomes partial (around 70%) height and it looks bad.
https://linear.app/autokitteh/issue/UI-1277/stretch-the-homepage-to-full-height-on-login-and-templates-filter

fix(UI-1277): update height dashboard and intro components

---

src/components/organisms/triggers/table/popoverContent.tsx
src/locales/en/tabs/translation.json
src/types/components/tables/triggersTable.type.ts

In the trigger info popover - check if connectionId is not defined, show error message
https://linear.app/autokitteh/issue/UI-1268/trigger-connectionid-not-defined-error

fix(UI-1268): enhance connection ID display in popover

---

src/components/organisms/dashboard/projectsTable.tsx
src/components/organisms/deployments/sessionStats.tsx
src/components/organisms/deployments/tableContent.tsx

On the home page it's almost round:
On the deployments page it is an ellipse:
In the design, it's almost round like on the home page:
https://www.figma.com/design/klCZL68fUd6pw0DEu0Sj7f/Autokitteh%3A-Look-%26-Feel-design-versions?node-id=3893-131806&t=gOCQGbQfhGCII5PY-4
https://linear.app/autokitteh/issue/UI-1241/hover-on-sessions-filter-should-be-circle-not-ellipse

refactor(UI-1241): improve styling for session stats and table content circle

---

src/components/organisms/deployments/sessionStats.tsx
src/components/organisms/deployments/tableContent.tsx

click between statuses or near the status (when we don't see the hover) should take us to all sessions filter and not by status
https://linear.app/autokitteh/issue/UI-1289/session-stats-click-on-empty-space

fix(UI-1289): fix deployment row click handling in table

---

src/locales/en/deployments/translation.json

Translation bug on activities and sessions:
https://linear.app/autokitteh/issue/UI-1299/translation-bug-on-activities-and-sessions

fix(UI-1299): fix translation keys in session outputs and activities

---

src/components/organisms/triggers/formParts/fileAndFunction.tsx
src/components/organisms/triggers/formParts/nameAndConnection.tsx
src/locales/en/tabs/translation.json
src/validations/trigger.schema.ts

The user shouldn't be able to save a trigger without file and function.
Check on all trigger types: connection, scheduler, webhook
https://linear.app/autokitteh/issue/UI-1300/disable-trigger-save-without-file-and-function

fix(UI-1300): add required fields for entry function and file path in trigger form

---

src/components/organisms/connections/integrations/slack/edit.tsx

Can't edit Slack connections
Observed in my local server (head = main branch), not in prod.
After initializing a Slack OAuth connection, the auth_type is set (by the frontend, not the backend) to "oauthDefault". This is fine, but the web UI (v2.135.0) doesn't know this value yet, so if the user tries to edit the connection, they see this:
https://linear.app/autokitteh/issue/UI-1321/cant-edit-slack-connections

fix(UI-1321): fix slack oauth edit

---

src/components/organisms/sidebar/userMenu.tsx
src/store/useOrganizationStore.ts

If we add someone to a new organization, we want him/her to see the new organization in his/her organizations list on the next refresh.
Every open user settings popover refresh organizations
https://linear.app/autokitteh/issue/UI-1315/refresh-organizations-list-on-any-page-refresh

feat(UI-1315): update refresh organizations list on any page

---

src/components/organisms/editorTabs.tsx
src/interfaces/store/sharedBetweenProjectsStore.interface.ts
src/store/useSharedBetweenProjectsStore.ts

When we move between files in the same project - keep the cursor on the same line and column when we back to file
https://linear.app/autokitteh/issue/UI-1301/keep-cursor-moving-between-files-in-the-same-project

feat(UI-1301): add cursor position line and column in file

---

src/components/molecules/templateIntegrationsIcons.tsx
src/components/organisms/templateStart.tsx

https://linear.app/autokitteh/issue/UI-1369/change-size-integration-icons

feat(UI-1369): add size prop to TemplateIntegrationsIcon

---

src/components/organisms/topbar/project/manualRun/manualRunButtons.tsx

Fix - deployments table shows the new deployment, but manual run is disabled (as if there are no deployments)
https://linear.app/autokitteh/issue/UI-1298/cant-do-manual-run-after-deploying-from-cli

fix(UI-1298): simplify run button disable logic

---

src/components/organisms/topbar/dashboard.tsx

https://linear.app/autokitteh/issue/UI-1379/remove-addimport-project-buttons-from-mobile-introlanding-page

fix(UI-1379): hide create and import buttons on mobile

---

src/components/organisms/connections/integrations/integrationEditForm.tsx
src/enums/components/connection.enum.ts
src/enums/components/index.ts

Fix Slack and GitHub edit mode - (when auth_type select is not disabled) - don’t show “oauth” option, only “oauthXXX”
https://linear.app/autokitteh/issue/UI-1376/fix-slack-and-github-edit-mode-when-auth-type-select-is-not-disabled

feat(UI-1376): fix filtering for connection type options on edit form

---

src/components/organisms/triggers/edit.tsx

When we have a trigger with some value, for example: data.text == "break-glass"
When we delete the filter in our frontend, the frontend won't send it to the backend, because the value is empty, the key will drop in the data object.
**The solution is:** to send a dot (".") to the backend, it will interpolate it as an empty value.
https://linear.app/autokitteh/issue/UI-1413/in-case-of-an-empty-filter-value-in-trigger-send-a-dot

fix(UI-1413): fix saving trigger with empty filter value

---

src/store/useTemplatesStore.ts

Current state: when we fetch new templates, the store doesn't erase the old files.
https://linear.app/autokitteh/issue/UI-1425/templates-indexeddb-contains-old-files

fix(UI-1425): remove old templates from indexed-db on new templates loading

---

src/components/organisms/editorTabs.tsx

When the user edits his code in a file editor, then he goes to other pages, other projects, when he's back, we should display the editor focused on the same line.
https://linear.app/autokitteh/issue/UI-1393/open-file-on-the-same-line-when-coming-back-from-sessions-page

fix(UI-1393): fix save cursor postion on editor code

---

src/components/organisms/deployments/sessions/table/table.tsx
src/constants/global.constants.ts
src/constants/index.ts
src/constants/sessions.constants.ts
src/services/sessions.service.ts

Expected flow when the user clicks the Sessions button in the navigation bar:
1.Run sessions.List filtered by projectId with pageSize=1
2.navigate to the session's page
https://linear.app/autokitteh/issue/UI-1398/always-select-first-session-on-sessions-page

refactor(UI-1398): always open first session on Sessions page

---

src/components/organisms/deployments/sessions/table/table.tsx
src/components/organisms/editorTabs.tsx
src/components/organisms/splitFrame.tsx
src/interfaces/store/projectStore.interface.ts
src/interfaces/store/sharedBetweenProjectsStore.interface.ts
src/store/useProjectStore.ts
src/store/useSharedBetweenProjectsStore.ts

Remember full screen between projects - unless the project have no files open in editor
https://linear.app/autokitteh/issue/UI-1361/remember-full-screen-between-projects-unless-the-project-have-no-files

feat(UI-1361): remember full screen between projects

---

src/components/organisms/deployments/sessions/table/table.tsx
src/components/organisms/deployments/sessions/viewer.tsx
src/constants/index.ts
src/constants/sessions.constants.ts
src/enums/eventListenerNames.enum.ts
src/services/sessions.service.ts

If the user runs Manual Run from the Sessions page - after Manual Run request succeed, we should refresh the sessions list.
Also Refresh the sessions list in the table after remove session
https://linear.app/autokitteh/issue/UI-1397/update-sessions-list-on-manual-run-in-the-sessions-page

feat(UI-1397)(UI-1400)(UI-1422): update sessions list on Manual Run in the Sessions page

---

src/components/organisms/activeDeploymentWarningModal.tsx
src/components/organisms/connections/deleteModal.tsx
src/components/organisms/modals/deleteDrainingDeploymentProjectModal.tsx
src/components/organisms/modals/deleteProjectModal.tsx

Change min modal button (ok) width
https://linear.app/autokitteh/issue/UI-1283/min-modal-button-ok-width

refactor(UI-1283): refactor button 'ok' minimum width in modals

---

src/components/organisms/settings/user/profile.tsx
src/components/templates/settingsLayout.tsx

User can't see full profile page because there's no scrolling - fix it
https://linear.app/autokitteh/issue/UI-1465/user-cant-see-full-profile-page-because-theres-no-scrolling

fix(UI-1465): adjust scrolling in profile page

---

src/app.tsx
src/components/organisms/settings/organization/members/table.tsx
src/components/organisms/settings/organization/switchOrganization.tsx
src/components/organisms/sidebar/userMenu.tsx
src/components/templates/settingsLayout.tsx
src/constants/index.ts
src/constants/navigation.constants.ts
src/interfaces/components/menu.interface.ts

For not-admin users, display the Organization Settings column without the , only Members, and display the same members' table as the regular admin without add.
https://linear.app/autokitteh/issue/UI-1411/allow-users-not-admins-see-the-members-list-in-an-organization

feat(UI-1411): add allow users see the memberts list in an organization

---

src/components/organisms/connections/integrations/github/authMethods/oauthPrivate.tsx
src/constants/connections/integrationVariablesMapping.constants.ts
src/constants/connections/integrationsDataKeys.constants.ts
src/locales/en/integrations/translation.json
src/validations/connection.schema.ts

Add a new input field for App Name in the GitHub private OAuth connection form.
Use app_name as the key to match the backend variable name.
https://linear.app/autokitteh/issue/UI-1475/add-app-name-field-in-github-private-connection

feat(UI-1475): add app name field to OAuth private form and validation schema

---

src/components/organisms/deployments/sessions/viewer.tsx
src/interfaces/models/session.interface.ts
src/locales/en/deployments/translation.json
src/models/session.model.ts
src/models/value.model.ts
src/services/sessions.service.ts
src/utilities/convertWrappedJson.utils.ts

Add memo json as inputs and later outputs
https://linear.app/autokitteh/issue/UI-1467/session-viewer-add-outputs-memo

feat(UI-1467): add memo support in session viewer and model

---

src/components/organisms/connections/table.tsx
src/hooks/useProjectActions.tsx
src/interfaces/store/connectionStore.interface.ts
src/store/useConnectionStore.ts

Description:
after creating an unsuccessful connection and deleting it we receive an error in the system logs.
Steps to reproduce: 
create a slack an unsuccessful private OAuth connection (use random values for the credentials), and save it 
delete it 
Current behavior: 
we get the errors mentioned above until we refresh.
Expected behavior:
don't receive any errors after deleting the connection.
https://linear.app/autokitteh/issue/UI-1483/receive-error-after-deleting-an-unsuccessful-connection

fix(UI-1483): reset connection checker on error in status check

---

src/components/organisms/deployments/sessions/tabs/activities/infiniteList.tsx
src/hooks/useVirtualizedList.tsx

Session opened - load 5 requests each request 50
https://linear.app/autokitteh/issue/UI-1534/load-all-activites-refactor

feat(UI-1534): limit activites loading in first time

---

src/components/molecules/select/base.tsx
src/components/organisms/triggers/formParts/fileAndFunction.tsx
src/components/organisms/triggers/formParts/nameAndConnection.tsx
src/components/organisms/triggers/formParts/scheduler.tsx
src/interfaces/components/forms/select.interface.ts
src/validations/trigger.schema.ts

This PR fixes the validation display for schedule triggers to show  asterisks (*) for required fields in the form.
UI-1598
- Add `isRequired` prop to Select component interface and implementation
- Update schedule trigger form fields to show asterisks (*) for required
fields when schedule trigger type is selected
- Fix validation schema to properly validate required fields for
schedule triggers
- File, Function Name, and Cron Expression fields now display asterisks
when schedule trigger type is selected
- Connection field now shows asterisk as it's always required
1. Navigate to triggers page
2. Click "Add Trigger"
3. Select "Schedule" as trigger type
4. Verify that File, Function Name, and Cron Expression fields show
asterisks (*)
5. Verify validation works properly when submitting empty …

fix(UI-1598): schedule triggers validation display

---

src/components/organisms/deployments/sessions/table/table.tsx

It doesn't happen every time, but it happens very frequently when switching from the sessions to deployments 
steps to reproduce:
go into any project that have sessions and deployments 
click on sessions 
then click on deployments
if it doesnt happen from the first time try switching from sessions to deployments couple of times until you get the error 
https://linear.app/autokitteh/issue/UI-1490/when-switching-from-sessions-to-deployments-we-get-404

fix(UI-1490): fix navigation from sessions to deployments page

---

src/components/organisms/topbar/project/navigation.tsx

Prevent user confusion by disabling the appropriate AI navigation button based on current mode when the chatbot drawer is open:
- Disable Config button when in config mode
- Disable Chat button when in chatbot mode

fix: disable conflicting AI navigation buttons when drawer is open

---

src/components/organisms/editorTabs.tsx
src/factories/fileOperations.ts

Problem
Users experienced data loss when editing files: after saving changes, closing the editor tab, and
reopening the file, their changes would disappear. Sometimes the new version would appear later
unexpectedly.
Root Cause
Two cache synchronization bugs in the file save flow:
1. Silent failure handling: saveFile() returned undefined instead of false on backend errors,
causing the UI to incorrectly treat failed saves as successful
2. Stale cache after save: The in-memory useCacheStore.resources cache was never updated after
successful saves, so reopening files loaded outdated content from memory instead of the newly
saved data
Solution
Fixed cache invalidation in src/factories/fileOperations.ts:
- Return false explicitly on backend save errors instead of undefined
- Force refresh the …

fix(UI-1762): resolve file editor cache inconsistency causing data loss

---

src/components/pages/project.tsx
src/hooks/usePopover.ts
src/interfaces/components/popover.interface.ts
src/locales/en/global/translation.json
tailwind.config.cjs

This PR enhances the project navigation toggle buttons by adding informative hover popovers with browser-like delay timing, fixes a critical z-index bug,
and extends the popover system with delay functionality.
**Main bug-fix: the "Hide Project Configuration" button was rendered behind project tabs due to lower z-index (z-40 vs tabs' z-[60])**
- Impact: Users had difficulty clicking the hide button as it was obscured by overlapping elements
- Solution: Increased z-index to z-[2010] for popover content and proper button wrapper positioning
**Enhanced Popover System with Delay Support**
- Extended PopoverOptions interface to include delay?: number | { open?: number; close?: number }
- Updated usePopover hooks to pass delay configuration to Floating UI's useHover
- Added 500ms delay …

fix(UI-1767): fix the assets pane expand button when it close

---

src/components/templates/descopeMiddleware.tsx

**Issue:** Login buttons were missing after authentication failures, leaving users unable to retry login.
**Root Cause:** After login failures, the code was calling clearAuthCookies() directly but not properly resetting the Descope component state, which
prevented the login UI from re-rendering.
**Solution:**
- Created unified resetDescopeComponent() function that handles both cookie clearing and component state reset
- Replaced direct clearAuthCookies() calls with resetDescopeComponent() in error handlers
- Added an optional parameter to control whether cookies should be cleared (useful for successful logins)
- Ensures login buttons are properly displayed after failed login attempts
Technical Details: The fix consolidates cleanup logic into a single function that increments …

fix(UI-1771): display login buttons if the login failed

---

src/components/organisms/editorTabs.tsx
src/locales/en/dashboard/translation.json
src/locales/en/errors/translation.json

This PR fixes cursor position preservation and editor state management issues in the Monaco editor when switching between projects and files.
The editor was experiencing inconsistent behavior when switching contexts:
1. **Cursor position loss**: Position wasn't restored reliably when switching between files/projects
2. **Content loading synchronization**: State restoration attempted before content was fully loaded
3. **Complex state management**: Unnecessary focus/typing state tracking causing race conditions
4. **Over-engineered event handling**: Unused selection tracking and excessive listeners
- Added `contentLoaded` state flag to ensure cursor restoration waits for content
- Combined content setup and cursor restoration into a single effect
- Proper sequencing: content load → content …

fix(UI-1766): preserve cursor position moving from and to the editor

---

src/components/molecules/jsonViewer.tsx
src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
src/models/activity.model.ts
src/models/session.model.ts
src/utilities/convertProtoValue.ts

Fixed a TypeError: `Cannot convert undefined or null to object error` in the JsonViewer by identifying that
**null**/**undefined** values from activity return values, session inputs, and event data were causing `Object.keys()` to fail in the **@uiw/react-json-view** library. 
We resolved this at the source level by modifying the `safeParseObjectProtoValue` utility function to return {} instead of **undefined**, and enhanced the activity model's **null** handling, ensuring all data passed to UI components is always a valid object.

fix(UI-1882): proto objects conversion

---

src/components/organisms/sidebar/sidebar.tsx

Fixed a race condition in the sidebar that caused errors during login.
The sidebar's useEffect was calling `getEnrichedOrganizations()` immediately when both `user` and `currentOrganization` became truthy. However, `getEnrichedOrganizations()` internally requires `currentOrganization` to be fully initialized in the store state, which wasn't guaranteed at the time of the call.
This timing issue caused error logs on login as the function would execute before the organization data was properly synchronized in the store.
Validate we have currentOrganization before we call `getEnrichedOrganizations()`
https://linear.app/autokitteh/issue/UI-1911/fix-failed-to-fetch-organizations-error-on-login

fix(UI-1911): prevent getEnrichedOrganizations call before currentOrg exist
