- src/components/organisms/deployments/sessions/table.tsx
Stop the sessions table from flickering when moving between status filters or reload, avoid this:
https://github.com/user-attachments/assets/d8f4948d-5d0b-44af-8330-c039eb9cf5d1
https://linear.app/autokitteh/issue/UI-771/stop-sessions-table-from-flickering-when-moving-between-status-filters
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code …
> fix: sessions filter and loading states smoother experience

- src/components/organisms/deployments/sessions/table.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/constants/index.ts
- src/constants/sessions.constants.ts
- src/hooks/useVirtualizedList.tsx
Sessions loading optimization - make pageSize bigger, current state:
https://github.com/user-attachments/assets/5bb721cc-be20-48b4-9e68-d79be254995a
https://linear.app/autokitteh/issue/UI-772/sessions-loading-optimization-make-pagesize-bigger
- …
> refactor: sessions table page size optimization

- src/app.tsx
- src/components/organisms/deployments/sessions/table.tsx
- src/components/organisms/deployments/sessions/tabs/outputs.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/components/organisms/deployments/table.tsx
- src/components/organisms/index.ts
- src/components/organisms/outputTabs.tsx
- src/components/organisms/sidebar/sidebar.tsx
- src/components/organisms/splitFrame.tsx
- src/components/organisms/systemLog.tsx
- src/components/pages/dashboard.tsx
- src/components/pages/intro.tsx
- src/components/pages/notFound404.tsx
- src/components/pages/project.tsx
- src/components/templates/appLayout.tsx
- src/constants/index.ts
- src/constants/resize.constants.ts
- src/featureFlags.ts
- src/hooks/useResize.tsx
- src/interfaces/hooks/useResize.interface.ts
- src/interfaces/store/loggerStore.interface.ts
- src/locales/en/projects/translation.json
- src/store/useLoggerStore.ts
https://linear.app/autokitteh/issue/UI-747/system-log
-   [ ] ☑️ (chore) - Chores - Other …
> feat: add system log

- src/components/atoms/loader.tsx
- src/components/molecules/menu/menu.tsx
- src/interfaces/components/loader.interface.ts
Display loading state on create project from main menu
https://linear.app/autokitteh/issue/UI-753/on-main-menu-create-new-project-add-loader …
> refactor: display loading state on create project from main menu

- src/components/organisms/connections/integrations/github/authMethods/oauth.tsx
- src/components/organisms/connections/integrations/googleGemini/add.tsx
- src/components/organisms/connections/integrations/slack/authMethods/oauth.tsx
- src/constants/lists/connections/options.constants.ts
- src/enums/components/connection.enum.ts
- src/locales/en/integrations/translation.json
1. [Sort integrations when selecting for a new connection](https://linear.app/autokitteh/issue/UI-692/sort-integrations-when-selecting-for-a-new-connection): The list needs to be sorted alphanumerically by the display name of the integrations
2. [Missing line break in Google Gemini info links](https://linear.app/autokitteh/issue/UI-701/missing-n-in-google-gemini-info-links)
3. [Update "more information" links for all integrations and all auth types:](https://linear.app/autokitteh/issue/UI-699/update-more-information-links-for-all-integrations-and-all-auth-types) Also, various (but not all) OAuth connection types include a message between the "More Information" links and the "Start OAuth Flow" button - get rid of these messages.
4. [Incorrect OAuth auth type title in all Google …
> refactor: improve and correct connections UI

- src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
Fix KWArgs table heading padding:
https://linear.app/autokitteh/issue/UI-750/fix-padding-in-kwargs-table-in-session-activity …
> fix: add left padding to kw-args table in session activity

- src/constants/monacoLanguages.constants.ts
Display markdown format and color in editor like this:
https://linear.app/autokitteh/issue/UI-779/display-markdown-format-and-color-in-editor …
> feat: display markdown colored in our editor

- src/components/atoms/buttons/index.ts
- src/components/atoms/buttons/resizeButton.tsx
- src/components/atoms/index.ts
- src/components/organisms/deployments/sessions/table.tsx
- src/components/organisms/splitFrame.tsx
- src/components/pages/dashboard.tsx
- src/components/pages/intro.tsx
- src/components/templates/appLayout.tsx
https://linear.app/autokitteh/issue/UI-729/drag-pane-separator
-   [ ] ☑️ (chore) - Chores - …
> feat: add new drag pane separator

- src/constants/namespaces.logger.constants.ts
- src/hooks/useCreateProjectFromTemplate.tsx
- src/locales/en/dashboard/translation.json
Fix message type from error to info:
https://linear.app/autokitteh/issue/UI-798/modify-project-successfully-created-message-type-from-error-to-info …
> fix: modify project successfully created message type from error to info

- src/components/organisms/sidebar/sidebar.tsx
https://linear.app/autokitteh/issue/UI-800/fix-failed-to-execute-contains-on-node-parameter-1-is-not-of-type-node …
> refactor: sidebar component to fix mouse leave event handling

- src/components/organisms/topbar/project/manualRun/manualRunButtons.tsx
- src/components/organisms/topbar/project/manualRun/manualRunParamsForm.tsx
- src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
- src/constants/namespaces.logger.constants.ts
- src/interfaces/components/forms/index.ts
- src/interfaces/components/forms/manualRunForm.interface.ts
- src/interfaces/store/manualRunStore.interface.ts
- src/locales/en/deployments/translation.json
- src/locales/en/validations/translation.json
- src/services/sessions.service.ts
- src/store/useManualRunStore.ts
- src/types/components/form.type.ts
- src/utilities/index.ts
- src/utilities/transformAndStringifyValues.utils.ts
- src/validations/manualRun.schema.ts
- src/validations/variable.schema.ts
Add an option to send data as JSON to manual run instead of the current key-value.
Add a toggle/dropdown selection between key-value and JSON like this:
https://linear.app/autokitteh/issue/UI-778/manual-run-add-json-parameters …
> feat: manual run with json

- .github/workflows/build_test_and_release.yml
- release.config.mjs
To validate in our backend that the WebUI code is genuine, added a hash file.
https://linear.app/autokitteh/issue/UI-796/add-sha256-hash-file-to-our-distribution-zip
-   [x] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration files …
> ci: add hash file of our distribution file

- src/locales/en/errors/translation.json
- src/locales/en/tabs/translation.json
Fixed incorrect translate
-   [ ] ☑️ (chore) - Chores - Other changes that don't modify src or …
> fix: translation key for successful file removal

- src/components/organisms/topbar/project/manualRun/manualRunSuccessToastMessage.tsx
- src/locales/en/deployments/translation.json
https://linear.app/autokitteh/issue/UI-811/manual-run-success-toast-link-text
-   [ ] ☑️ …
> refactor: manualRun improve button styling and add "Show more" option

- src/components/organisms/dashboard/projectsTable.tsx
-   [ ] ☑️ (chore) - Chores - Other changes that don't modify src or test files
-   [ ] ↩️ …
> refactor: update table styling in DashboardProjectsTable component

- src/assets/new_project_program/program.py
- src/constants/project.constants.ts
- src/store/useProjectStore.ts
- vite.config.ts
The default project program file was erased by mistake in: https://github.com/autokitteh/web-platform/commit/ba6930738bc25ffd3b17ad1f4a6b26a285eb17c8
https://linear.app/autokitteh/issue/UI-823/creating-a-new-project-in-prod-generates-a-programpy-with-html-inside
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, missing …
> fix: place back missing new project program file

- src/components/organisms/dashboard/welcomeMainBlock.tsx
- src/components/organisms/introMainBlock.tsx
Fix this warning:
https://linear.app/autokitteh/issue/UI-820/fix-asset-image-warning-in-build
- …
> refactor: fix image path to avoid warning in build

- src/assets/templates/categorize_emails/README.md
Update README from kittehub.
Based on this PR: https://github.com/autokitteh/kittehub/pull/103
https://linear.app/autokitteh/issue/UI-826/update-categorize-emails-readme-from-kittehub …
> chore: update readme file for categorize_emails template

- src/components/organisms/systemLog.tsx
- src/services/logger.service.ts
https://linear.app/autokitteh/issue/UI-652/logger-color-statuses
-   [ ] ☑️ (chore) - Chores - …
> refactor: update logger output color

- src/components/organisms/dashboard/welcomeInfoCard.tsx
- src/components/organisms/dashboard/welcomeMainBlock.tsx
- src/components/organisms/introMainBlock.tsx
- src/components/organisms/topbar/dashboard.tsx
- src/components/pages/intro.tsx
1. Minimum Template card width
2. Boxes height relatively to the screens - change boxes height with screen height
https://linear.app/autokitteh/issue/UI-706/intro-design-large-screens …
> refactor: improve intro - Design large screens

- index.html
The browser displays translate from Hebrew suggestions, which is irrelevant since our app is in English:
https://linear.app/autokitteh/issue/UI-824/browser-asks-to-translate-from-hebrew …
> fix: change website language in index.html to english instead of hebrew

- src/components/molecules/modal.tsx
- src/components/organisms/dashboard/welcomeVideoModal.tsx
- src/components/templates/settingsLayout.tsx
https://linear.app/autokitteh/issue/UI-757/fix-video-modals-in-intro-page
-   [ ] ☑️ (chore) - …
> refactor: modal and settings layout styles

- src/assets/image/pages/login/index.ts
Fix the following error in the build:
Removed the import, since we import the file dynamically in `src/components/pages/login.tsx`
https://linear.app/autokitteh/issue/ENG-1747/fix-svg-import-warning-in-the-build
-   [x] 🏎 (perf) - Optimization …
> perf: dynamic svg import warning in build

- src/components/molecules/refreshButton.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/components/organisms/deployments/table.tsx
- src/constants/index.ts
- src/interfaces/components/button.interface.ts
https://linear.app/autokitteh/issue/UI-859/deployments-display-loader-only-on-first-load-dont-blink-on-following
https://linear.app/autokitteh/issue/UI-853/session-viewer-disable-refresh-if-the-status-is-finished …
> refactor: table deployments loader and viewer refresh button

- e2e/project/trigger.spec.ts
- e2e/project/variable.spec.ts
- src/components/organisms/connections/deleteModal.tsx
- src/components/organisms/connections/edit.tsx
- src/components/organisms/connections/integrations/asana/edit.tsx
- src/components/organisms/connections/integrations/aws/edit.tsx
- src/components/organisms/connections/integrations/discord/edit.tsx
- src/components/organisms/connections/integrations/googleGemini/edit.tsx
- src/components/organisms/connections/integrations/integrationEditForm.tsx
- src/components/organisms/connections/integrations/openAI/edit.tsx
- src/components/organisms/index.ts
- src/components/organisms/triggers/deleteModal.tsx
- src/components/organisms/triggers/edit.tsx
- src/components/organisms/variables/deleteModal.tsx
- src/components/organisms/variables/edit.tsx
- src/components/organisms/warningDeploymentActivetedModal.tsx
- src/enums/components/modal.enum.ts
- src/hooks/useConnectionForm.ts
- src/interfaces/components/index.ts
- src/interfaces/components/modal.interface.ts
- src/interfaces/store/cacheStore.interface.ts
- src/locales/en/modals/translation.json
- src/store/cache/useCacheStore.ts
https://linear.app/autokitteh/issue/UI-810/when-there-is-active-deployment-and-edit-asset-display-warning …
> feat: add Warning Modal triggers/connections/variables

- src/hooks/useCreateProjectFromTemplate.tsx
On project open - display assets not connections
https://linear.app/autokitteh/issue/UI-872/on-project-open-display-assets-not-connections …
> refactor: redirect to code after project creation from template

- src/components/molecules/idCopyButton.tsx
- src/components/molecules/index.ts
- src/components/organisms/deployments/sessionStats.tsx
- src/components/organisms/deployments/tableContent.tsx
- src/locales/en/components/buttons/translation.json
- src/locales/en/deployments/translation.json
1. Add titles on deployment columns
2. Remove bold from time
3. Build ID - first seven chars copy only
4. Change running column numbers to blue
https://linear.app/autokitteh/issue/UI-848/deployments-table-fixes …
> refactor: deployments table - modify column titles for session statuses

- src/app.tsx
- src/assets/image/icons/ListDetails.svg
- src/assets/image/icons/index.ts
- src/components/molecules/menu/menu.tsx
- src/components/organisms/events/index.ts
- src/components/organisms/events/table.tsx
- src/components/organisms/events/table/header.tsx
- src/components/organisms/events/table/row.tsx
- src/components/organisms/events/table/virtualizer.tsx
- src/components/organisms/events/viewer.tsx
- src/components/organisms/index.ts
- src/components/organisms/sidebar/sidebar.tsx
- src/constants/namespaces.logger.constants.ts
- src/locales/en/errors/translation.json
- src/locales/en/events/translation.json
- src/locales/en/menu/translation.json
- src/locales/en/sidebar/translation.json
- src/models/event.model.ts
- src/services/events.service.ts
- src/types/models/event.type.ts
https://linear.app/autokitteh/issue/UI-661/single-event-viewer-on-row-click
-   [ ] ☑️ (chore) …
> feat: add page event view

- src/services/index.ts
- src/services/indexedDb.service.ts
- src/services/templatesIndexedDb.service.ts
Continue of https://github.com/autokitteh/web-platform/pull/599
as a part of the big PR:
https://github.com/autokitteh/web-platform/pull/610
https://github.com/autokitteh/web-platform/pull/577
https://linear.app/autokitteh/issue/UI-898/fetch-templates-from-github-in-the-runtime-and-display-in-the-ui
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the …
> feat: template files service using indexed-db

- src/interfaces/store/activitiesAndOutputsCache.store.interface.ts
- src/store/cache/useActivitiesCacheStore.ts
- src/store/cache/useOutputsCacheStore.ts
Bug: Session activities doesn't update while the session is running
Page reload in the browser fixes it, but the proper way should be using the session refresh.
https://github.com/user-attachments/assets/8a735b16-2e09-4c7d-bfa2-95aee4ee8b26
https://linear.app/autokitteh/issue/UI-884/session-activities-doesnt-update-while-the-session-is-running
-   [ ] 🎨 (style) - Styles - …
> fix: refresh output and activities state on hard reload

- src/assets/templates/quickstart/README.md
Get the latest change in quickstart readme in kittehub
https://linear.app/autokitteh/issue/UI-896/get-latest-change-in-quickstart-readme-in-kittehub …
> feat: update sample templates from kittehub

- src/components/organisms/introMainBlock.tsx
Fix browser error for proper structure:
https://linear.app/autokitteh/issue/UI-892/fix-browser-error-for-proper-structure …
> fix: fix browser error for proper elements hierarchy

- src/components/organisms/dashboard/welcomeInfoCard.tsx
Make buttons larger:
https://linear.app/autokitteh/issue/UI-897/fix-play-button-is-safari-browser …
> fix: change play buttons design

- src/constants/dashboard.constants.ts
The file was missing in the files array, therefore it wasn't published on the template creation.
https://linear.app/autokitteh/issue/ENG-1752/slack-support …
> fix: add missing filename to the slack_support template

- src/components/organisms/settings/clientConfiguration.tsx
- src/locales/en/services/translation.json
- src/services/auth.service.ts
Use the gRPC Auth service, CreateToken function instead of Axios POST
https://linear.app/autokitteh/issue/UI-902/fix-createtoken-in-settings …
> fix: user auth token creation

- src/components/templates/descopeMiddleware.tsx
- src/locales/en/login/translation.json
- src/services/logger.service.ts
Continuing this ticket: [UI-901](https://linear.app/autokitteh/issue/UI-901/include-discord-connection-error-message)
Log the proper error from the backend - log only to the console, not the system logger.
https://linear.app/autokitteh/issue/UI-903/fix-login-error-handling
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, …
> fix: login page readable error on ak server error response

- e2e/fixtures.ts
- src/components/molecules/select/base.tsx
- src/components/molecules/select/creatable.tsx
- src/components/molecules/select/index.ts
- src/components/molecules/select/select.tsx
- src/components/organisms/triggers/add.tsx
- src/components/organisms/triggers/formParts/fileAndFunction.tsx
- src/components/organisms/triggers/table.tsx
- src/constants/featureFlags.constants.ts
- src/interfaces/components/forms/select.interface.ts
- src/validations/trigger.schema.ts
- src/vite-env.d.ts
- vite.config.ts
https://linear.app/autokitteh/issue/UI-910/creatable-component
-   [ ] ☑️ (chore) - Chores - …
> feat: create CreatableSelect component

- src/constants/lists/connections/options.constants.ts
Update aws connection regions list.
The new list taken from here:
https://www.aws-services.info/regions.html
https://linear.app/autokitteh/issue/UI-874/update-the-list-of-aws-regions …
> fix: update aws connection regions list

- .github/workflows/build_test_and_release.yml
- package.json
Fix CI issues after templates PR released:
An issue for example:
https://github.com/autokitteh/web-platform/actions/runs/11813992154/job/32912210314
https://linear.app/autokitteh/issue/UI-943/fix-ci-issues-after-templates-pr-released
-   [x] ⚙️ …
> fix: fix github actions release

- package-lock.json
- package.json
Fix eslint issues on windows.
Fix an error we have on commit and running eslint after the latest update.
https://linear.app/autokitteh/issue/UI-942/fix-eslint-issues-on-windows …
> fix:  dependencies for Windows

- src/app.tsx
- src/components/organisms/topbar/project/buttons.tsx
- src/components/organisms/topbar/project/projectConfig.tsx
- src/components/templates/appLayout.tsx
- src/enums/components/index.ts
- src/enums/components/topbar.enum.ts
- src/locales/en/deployments/translation.json
- src/types/components/index.ts
- src/types/components/topbar.type.ts
https://linear.app/autokitteh/issue/UI-930/topbar-join-all-states-and-display-on-all-screens
- …
> refactor: simplify appLayout and remove topbar variant logic

- src/components/organisms/code/addModal.tsx
- src/components/organisms/code/table.tsx
- src/components/organisms/editorTabs.tsx
- src/components/organisms/topbar/project/buttons.tsx
- src/components/organisms/topbar/project/projectConfig.tsx
- src/components/organisms/triggers/add.tsx
- src/components/organisms/triggers/edit.tsx
- src/components/pages/project.tsx
- src/hooks/useFileOperations.ts
- src/interfaces/components/index.ts
- src/interfaces/components/modal.interface.ts
- src/interfaces/store/cacheStore.interface.ts
- src/interfaces/store/fileStore.interface.ts
- src/store/cache/useCacheStore.ts
- src/store/useFileStore.ts
https://linear.app/autokitteh/issue/UI-923/cache-files
-   [ ] ☑️ (chore) - Chores - Other …
> feat: add to cache store files

- src/components/organisms/connections/integrations/integrationEditForm.tsx
When attempting to upload the JSON key file to establish a connection on the platform, the following error appears: 
ERROR: [Connection Form] Error while editing a connection, error:
https://github.com/user-attachments/assets/4e52ef6f-66da-47dd-bc02-bbcfa95f749a
https://linear.app/autokitteh/issue/UI-921/json-key-connection-error
-   [ ] 🎨 (style) - Styles - Changes that do …
> fix: fix saving google connection with json key on edit

- src/components/templates/descopeMiddleware.tsx
When the user logs in, he shouldn't see the logs he (or another user) had before.
https://linear.app/autokitteh/issue/UI-844/clear-logs-on-log-in …
> feat: clear system logs on user login

- src/components/templates/descopeMiddleware.tsx
Currently, when we log in, we see an error toast, but there is nothing in the system log.
The issue happens because of [ENG-1773](https://linear.app/autokitteh/issue/ENG-1773/successful-log-in-redirects-to-host-base-url).
Task: send the request so we won't have an error on login.
An example of a successful login:
https://github.com/user-attachments/assets/cdef6f1c-c17f-4fc2-a9e5-de275c8670be
And this is what we see in the browsers console:
https://linear.app/autokitteh/issue/UI-950/remove-error-toast-when-you-log-in
-   [ ] 🏎 (perf) - …
> fix: disable redirect on login response to avoid an error

- src/components/organisms/code/addModal.tsx
- src/components/organisms/code/table.tsx
- src/components/organisms/editorTabs.tsx
- src/hooks/useFileOperations.ts
- src/store/useFileStore.ts
When we add a new file, it isn't displayed in the list:
https://github.com/user-attachments/assets/6b6ec2d9-fdf6-408b-bd63-56f287e45710
https://linear.app/autokitteh/issue/UI-954/files-are-not-displayed-when-created …
> fix: display files on creation

- .github/workflows/build_test_and_release.yml
Fix missing flow.
https://linear.app/autokitteh/issue/UI-967/fix-cicd-distribution-and-sha
-   [x] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
- …
> fix: make the ci-cd create distribution files again

- src/locales/en/stores/translation.json
- src/store/useTemplatesStore.ts
We have untreated error throw in our code, refactor not to throw an error:
[UI-955: Fix fetch template files from github or from self](https://linear.app/autokitteh/issue/UI-955/fix-fetch-template-files-from-github-or-from-self) …
> fix: fetch template files from github or from self

- src/components/organisms/dashboard/templates/tabs/createModal.tsx
Fix this bug:
https://linear.app/autokitteh/issue/UI-959/fix-template-readme-link
-   [ ] ☑️ …
> fix: fix the readme file fetcher in create project from template modal

- src/components/organisms/editorTabs.tsx
Editor scrolls to the end of the file during typing with autosave enabled
https://github.com/user-attachments/assets/edfe6abf-eaa5-4b40-83cc-0e44ec978b02
https://linear.app/autokitteh/issue/UI-907/autosave-bug …
> fix: prevent editor jumping when autosave triggered

- src/components/organisms/events/viewer.tsx
- src/locales/en/events/translation.json
https://linear.app/autokitteh/issue/UI-915/event-viewer-display-refactor
-   [ ] ☑️ (chore) - …
> refactor: event viewer style

- src/components/organisms/deployments/sessions/tabs/activities/infiniteRow.tsx
- src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
- src/locales/en/deployments/translation.json
- src/models/activity.model.ts
**Remove function param names from activity card**
What we have today:
All functions in the execution flow have the same parameters; it works like that because of the way we process the workflow inside our python.
Optimization: remove the parameters and add a title to describe what this line means (function name):
https://linear.app/autokitteh/issue/UI-958/remove-function-param-names-from-activity-card
-   [ ] 📄 (test) - Tests - Adding missing tests or …
> feat(UI-958): remove function arguments from activity card title

- src/components/organisms/events/table/row.tsx
- src/components/organisms/events/viewer.tsx
- src/locales/en/events/translation.json
- src/models/event.model.ts
- src/types/models/event.type.ts
Change IDs display to copyID button all over the system
https://linear.app/autokitteh/issue/UI-941/change-ids-display-to-copyid-button-all-over-the-system …
> feat(UI-941): change id columns to copy buttons

- src/interfaces/store/connectionCheckerStore.interface.ts
- src/store/useConnectionCheckerStore.ts
Currently, we are running a checker after the OAuth process starts and saving the last connection interval, so if we delete the project, we will be able to stop the checker.
But it won't work if we start more than 1 OAuth flow. Then we keep only the latest connectionId checker, and when we remove the project, we stop only the last connection checker, not the rest of them.
**Task:** stop all connections checker, in case more than 1 started.
https://linear.app/autokitteh/issue/UI-968/remove-connections-checker-when-there-is-more-than-1-connection …
> fix(UI-968): stop connections checker for all connections in process

- src/constants/events.constants.ts
- src/constants/index.ts
- src/services/events.service.ts
- src/store/cache/useCacheStore.ts
Limit events to pull only last 500
https://linear.app/autokitteh/issue/UI-978/limit-events-to-pull-only-last-500 …
> feat(UI-978): limit events list display

- src/components/molecules/select/base.tsx
- src/locales/en/components/select/translation.json
When you're typing custom function name, instead of Use you see undefined, fix the label, from:
to: …
> fix(UI-988): fix missing creatable label

- src/components/organisms/topbar/project/buttons.tsx
Reproduction:
1. Work on a project - build
2. Go to another (new) project - click build
3. The files are swapped between the first and the second one
Example:
https://github.com/user-attachments/assets/f59c0944-d646-4d2d-9dab-c2dc5b143e5c
https://linear.app/autokitteh/issue/UI-1002/fix-files-swap-on-build
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of …
> fix(UI-1002): fix files swap between projects on build

- netlify.toml
The response does not include either Content-Security-Policy with 'frame-ancestors' directive or X-Frame-Options
to protect against 'ClickJacking' attacks.
Remedies:
Modern Web browsers support the Content-Security-Policy and X-Frame-Options HTTP headers. Ensure one of them is set on all web pages returned by your site/app. If you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. Alternatively consider implementing Content Security Policy's "frame-ancestors" directive.
Reference:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://linear.app/autokitteh/issue/ENG-1872/casa-dast-scan-1-missing-anti-clickjacking-head …
> fix(ENG-1872)(ENG-1873): add anti-clickjacking header and anti-mime-sniff

- netlify/edge-functions/404.ts
- package-lock.json
- package.json
The links in the report are showing a 404 page, but the HTTP status code of this page is 200, for example:
- /._darcs
- /.bzr
- /.hg
- /BitKeeper
https://linear.app/autokitteh/issue/ENG-1871/casa-dast-scan-1-hidden-files-found …
> fix(ENG-1718): return 404 status on 404 page

- package-lock.json
- package.json
In order to avoid dangerous `eval` JS function, updated `@sentry/react` to the latest.
https://linear.app/autokitteh/issue/ENG-1874/casa-dast-scan-1-dangerous-eval-js-function …
> chore(ENG-1874): update sentry-react package

- src/components/organisms/connections/integrations/confluence/authMethods/apiToken.tsx
- src/components/organisms/connections/integrations/jira/authMethods/apiToken.tsx
- src/constants/connections/integrationVariablesMapping.constants.ts
https://linear.app/autokitteh/issue/UI-1010/missing-values-in-edit-connections
-   [ ] ☑️ …
> fix(UI-1010): fix missing values in edit connections

- src/components/organisms/connections/integrations/jira/authMethods/apiToken.tsx
change "name@exemple.com" to "name@example.com" in New Jira Connection form:
https://linear.app/autokitteh/issue/UI-1011/fix-typo-in-jira-connection-creation-form
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration files …
> refactor(UI-1011): fix typo in add connection (jira) form

- src/assets/index.css
- src/components/organisms/dashboard/templates/tabs/tabs.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/components/pages/login.tsx
- src/locales/en/login/translation.json
- tailwind.config.cjs
Adjust login page to mobile devices
https://linear.app/autokitteh/issue/UI-1013/responsive-login-page …
> feat(UI-1013): adjust login page to mobile devices

- src/components/atoms/checkbox.tsx
- src/components/organisms/editorTabs.tsx
- src/interfaces/components/checkbox.interface.ts
Prevent cmd/ctrl+s in the editor from opening save page window
Instead of save this page window we would like simply to save the files we are working on.
https://github.com/user-attachments/assets/3a35fddb-01a5-4aee-b77e-741e864e33b9
https://linear.app/autokitteh/issue/UI-997/prevent-cmdctrls-in-the-editor-from-opening-save-page-window
-   [ ] 🎨 (style) - Styles - Changes that …
> feat(UI-997): cmd/ctrl+s in editor should save the code in it

- src/components/organisms/triggers/add.tsx
- src/components/organisms/triggers/edit.tsx
- src/components/organisms/triggers/formParts/fileAndFunction.tsx
- src/constants/featureFlags.constants.ts
- src/locales/en/tabs/translation.json
- src/vite-env.d.ts
- vite.config.ts
Remove the combo-box feature flag to always display the combo box in the form of the trigger add/edit.
https://linear.app/autokitteh/issue/UI-929/remove-the-combo-box-feature-flag-to-display-the-combo-box-in-the …
> refactor(UI-929): remove events list in triggers combobox feature flag

- package-lock.json
- package.json
- src/components/molecules/popover.tsx
- src/components/organisms/sidebar/sidebar.tsx
- src/hooks/usePopover.ts
- src/interfaces/components/popover.interface.ts
- src/locales/en/sidebar/translation.json
Adjustments:
1. Instead of an avatar, use this: https://www.npmjs.com/package/react-avatar to display initials (only initials, not avatar picture)
2. On click in the design we have: settings, logout, please add also the email and name like in the screenshot below:
https://linear.app/autokitteh/issue/UI-867/user-profile-bubble
-   [ ] 🎨 (style) - Styles - Changes that do not …
> feat(UI-867): user profile info in sidebar

- src/utilities/convertWrappedJson.utils.ts
When we have an error converting nested JSON value from the backend - for example session inputs or event payload, the user shouldn't know if we had an issue converting the output because:
1. He will see the issue with his data in the JSON viewer in the UI.
2. Even if he'll know that there was an error converting, he won't be able to affect it.
Bug:
https://github.com/user-attachments/assets/1e79e5b5-14db-4dbd-a358-7d6c92b054cb
https://linear.app/autokitteh/issue/UI-1000/event-issues
-   [ ] 📄 (docs) - …
> fix(UI-1000): prevent of json converter to write in system log

- netlify.toml
- src/app.tsx
- src/components/pages/external404.tsx
- src/components/pages/index.ts
- src/components/pages/internal404.tsx
- src/components/templates/descopeMiddleware.tsx
- src/mainApp.tsx
The links in the report are showing a 404 page, but the HTTP status code of this page is 200, for example:
- /._darcs
- /.bzr
- /.hg
- /BitKeeper
https://linear.app/autokitteh/issue/ENG-1871/casa-dast-scan-1-hidden-files-found …
> fix(ENG-1871): 404 path in the url should return 404 status

- src/components/organisms/code/addModal.tsx
Reproduce:
1. Create a new file
2. Close it
3. Create a new project
4. Try to create a new file - when typing the name, it doesn't write anything (writing and deleting the characters)
Example:
https://github.com/user-attachments/assets/e1a8fcb2-3da9-4b14-b930-ab53403c38ad
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, …
> fix(UI-1033): fix file creation after one file created

- src/components/atoms/frame.tsx
https://linear.app/autokitteh/issue/UI-1032/fix-top-space-in-frame
-   [ ] ☑️ (chore) - Chores …
> fix(UI-1032): adjust padding for improved layout consistency

- src/components/organisms/topbar/project/navigation.tsx
Fix incorrect behavior of the bottom line in the menu
https://github.com/user-attachments/assets/bd56711e-825a-4214-b5fa-09161f7fca9a
https://linear.app/autokitteh/issue/UI-1036/fix-line-in-topbar-menu …
> fix(UI-1036): update behavior of the bottom line in the menu

- src/constants/global.constants.ts
**Fix incorrect date format**:
Timestamps are currently displayed as "yyyy-dd-mm HH:MM:SS", for example: "2024-14-12 10:14:00".
But timestamp dates should always be "yyy-mm-dd …", i.e.: "2024-12-14 10:14:00".
In other words: it should be year-month-day, not year-day-month.
Confirmed in: deployments table, sessions table, events table, event details, system log panel. If there are other places where a timestamp is displayed I guess the same bug is there too.
https://linear.app/autokitteh/issue/UI-1056/incorrect-date-format-in-all-web-ui
-   [ ] …
> fix(UI-1056): change datetime format to 'YYYY-MM-DD HH:mm:ss'

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- package-lock.json
Update deps, to avoid security vulnerabilities:
https://linear.app/autokitteh/issue/UI-1071/update-dependencies-to-avoid-vulnerabilities
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration files and scripts (example scopes: …
> chore(UI-1071): update deps to avoid security vulnerabilities

- src/enums/components/connection.enum.ts
Change integration name from Jira to Atlassian Jira
https://linear.app/autokitteh/issue/UI-1080/change-integration-name-from-jira-to-atlassian-jira
> refactor(UI-1080): rename integration from jira to atlassian jira

- src/components/organisms/connections/integrations/googleGemini/add.tsx
Change auth_type from botToken to apiKey.
https://linear.app/autokitteh/issue/UI-1079/change-gemini-connection-type
> refactor(UI-1079): change gemini connection auth_type

- src/components/organisms/events/table/row.tsx
Mark the selected event with `bg-black` like this:
https://linear.app/autokitteh/issue/UI-1081/events-table-mark-selected-event …
> feat(UI-1081): mark selected event in events table

- src/components/atoms/table/tD.tsx
- src/components/organisms/dashboard/projectsTable.tsx
- src/components/organisms/deployments/sessions/table.tsx
- src/components/organisms/deployments/sessions/tableRow.tsx
- src/components/organisms/triggers/table.tsx
- src/locales/en/deployments/translation.json
Truncate all columns:
https://linear.app/autokitteh/issue/UI-1074/truncate-and-display-sessions-table-columns-with-ellipsis …
> fix(UI-1074): truncate and display sessions table columns with ellipsis

- src/components/organisms/events/table/header.tsx
- src/components/organisms/events/table/row.tsx
type is slash_command but all the user sees is slash_com
https://linear.app/autokitteh/issue/UI-1049/bug-event-type-is-truncated …
> fix(UI-1049): event table columns width and truncate

- src/utilities/convertBuildRuntimesToViewTriggers.utils.ts
Filter out functions beginning with lodash in manual run:
https://linear.app/autokitteh/issue/UI-999/filter-out-functions-beginning-with-lodash-in-manual-run …
> feat(UI-999): filter out functions beginning with lodash in manual run

- src/components/organisms/sidebar/index.ts
- src/components/organisms/sidebar/sidebar.tsx
- src/components/organisms/sidebar/userMenu.tsx
- src/constants/featureFlags.constants.ts
- src/constants/index.ts
- src/constants/navigation.constants.ts
- src/constants/navigation.constnants.ts
- src/featureFlags.ts
- src/locales/en/sidebar/translation.json
- src/vite-env.d.ts
- vite.config.ts
Create a menu design based on this Characterization: https://docs.google.com/presentation/d/1rzqpzDygY3cjqY8WARvuIciupgEiwPGs0RD51K3bBYc/edit#slide=id.g31c49cbe65a_1_165
https://linear.app/autokitteh/issue/UI-1058/create-menu-mockup
-   [ ] ⚙️ …
> feat(UI-1058): orgs & users - menu design

- src/constants/global.constants.ts
To avoid errors waiting less than 5 seconds, we will increase the timeout to 10 seconds.
https://linear.app/autokitteh/issue/UI-1083/increase-grpc-timeout-to-15-seconds
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration …
> feat(UI-1083): increase api timeout

- src/components/organisms/triggers/formParts/schedulerInfo.tsx
- src/constants/triggers.constants.ts
- src/locales/en/tabs/translation.json
Add the crontab guru link as the first help link - it's the most useful: https://crontab.guru/
Replace the Oracle and Temporal links with the help link in the scheduler sample in Kittehub: https://github.com/autokitteh/kittehub/tree/main/samples/scheduler#api-documentation
https://linear.app/autokitteh/issue/UI-1057/scheduler-help-links
-   [ ] 🎨 (style) - Styles - Changes …
> refactor(UI-1057): update trigger scheduler info links

- src/components/organisms/connections/edit.tsx
- src/components/organisms/connections/integrations/integrationEditForm.tsx
- src/hooks/useConnectionForm.ts
- src/locales/en/integrations/translation.json
- src/locales/en/services/translation.json
- src/services/connection.service.ts
Display connection when there is no integration
https://linear.app/autokitteh/issue/UI-1076/display-connection-when-there-is-no-integration …
> fix(UI-1076): improve logs and display connection when integration not found

- src/components/organisms/sidebar/sidebar.tsx
- src/locales/en/sidebar/translation.json
https://linear.app/autokitteh/issue/UI-1087/fix-sidebar-translations
-   [ ] ☑️ (chore) - …
> fix(UI-1087): fix menu translations

- src/components/organisms/dashboard/projectsTable.tsx
- src/components/organisms/topbar/dashboard.tsx
- src/components/pages/dashboard.tsx
- src/hooks/useWindowDimensions.ts
The issue was that the screen wasn't displaying the menu, therefore it wasn't loading the projects, therefore the loading state couldn't change
https://linear.app/autokitteh/issue/UI-1088/fix-login-on-mobile-devices …
> fix(UI-1088): fix login on mobile devices

- src/utilities/copyToClipboard.utils.ts
This is related to how the Clipboard API's security permissions work in web browsers. The Clipboard API (specifically navigator.clipboard.writeText()) is only available in secure contexts, which means:
The page must be served over HTTPS, OR
The page must be served from localhost
0.0.0.0 is not considered the same as localhost by browsers, even though they might resolve to the same place in your development environment. When you use 0.0.0.0, browsers don't grant it the same security permissions as localhost.
But if we want to run it on a non-secured URL, the copy button won't work.
https://linear.app/autokitteh/issue/UI-1086/fix-copy-button-to-work-on-not-secured-urls
-   [ ] 🔄 (refactor) - Code Refactoring - A …
> fix(UI-1086): fix copy button on not secured urls

- src/components/organisms/settings/profile/profile.tsx
- src/locales/en/settings/translation.json
Add description for a retention policy for the users.
https://linear.app/autokitteh/issue/UI-964/retention-policy-handling-ui …
> feat(UI-964): add retention policy in user settings

- package-lock.json
- package.json
- release.config.mjs
At this moment, no new version in GitHub has been written into package.json, since we removed the semantic-release/npm plugin.
https://linear.app/autokitteh/issue/UI-1094/fix-semantic-release-to-write-the-version-into-packagejson …
> fix(UI-1094): fix semantic-release to write the version into package.json

- src/services/projects.service.ts
Switch listForOwner to list in projects API because listForOwner is deprecated.
https://linear.app/autokitteh/issue/UI-1097/switch-listforowner-to-list-in-projects-api
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration …
> fix(UI-1097): switch projects list request

- src/components/organisms/sidebar/userMenu.tsx
Fix duplicate keys error:
https://linear.app/autokitteh/issue/UI-1098/fix-duplicate-keys-error …
> fix(UI-1098): update organization IDs in user menu

- src/components/organisms/sidebar/sidebar.tsx
Align the logo to the center.
Before:
After:
https://linear.app/autokitteh/issue/UI-1093/logo-not-centered …
> fix(UI-1093): centralize the logo

- src/components/organisms/deployments/sessions/table.tsx
- src/components/organisms/deployments/sessions/tableRow.tsx
Sessions table - change column width back to percents - In order to avoid states like this:
Change table columns width to percents.
After:
2K:
1920:
1440:
https://linear.app/autokitteh/issue/UI-1100/sessions-table-change-column-width-back-to-percents
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, …
> fix(UI-1100): sessions table - change column width back relative to resolution

- src/hooks/useCreateProjectFromTemplate.tsx
- src/locales/en/services/translation.json
- src/services/projects.service.ts
https://linear.app/autokitteh/issue/UI-1101/fix-project-creation-failed-message
-   [ ] ☑️ …
> fix(UI-1101): fix project creation failed message in the toast

- src/components/molecules/copyButton.tsx
- src/components/molecules/idCopyButton.tsx
- src/components/organisms/deployments/tableContent.tsx
- src/components/organisms/events/table/row.tsx
After changes in the event table - the build ID is almost invisible in the deployments table now:
https://linear.app/autokitteh/issue/UI-1113/fix-build-id-display-in-deployments-table …
> fix(UI-1113): fix id-copy-button to be visible on deployments table page

- index.html
Implemented by the explanation from here:
https://support.google.com/tagmanager/answer/14847097?hl=en&ref_topic=15191151&sjid=15209236849471240215-EU
https://linear.app/autokitteh/issue/UI-1112/add-googletagmanager-to-the-app …
> feat(UI-1112): add google tag manager

- package-lock.json
- package.json
update vited
https://linear.app/autokitteh/issue/UI-1104/update-all-deps-to-latest-versions
- …
> chore(UI-1104): update vite

- src/services/events.service.ts
Fix events payload viewer in JSON - The payload shouldn't be displayed as key-value:
But as readable JSON: …
> fix(UI-1116): events-viewer should display the payload as readable json

- src/components/organisms/dashboard/templates/tabs/createModal.tsx
Remove metadata in Create Project From Template README:
https://linear.app/autokitteh/issue/UI-998/remove-metadata-in-create-from-project-readme …
> feat(UI-998): remove readme.md metadata in create project from template

- src/components/organisms/triggers/add.tsx
- src/components/organisms/triggers/edit.tsx
- src/components/organisms/triggers/formParts/fileAndFunction.tsx
- src/components/organisms/triggers/formParts/webhook.tsx
- src/constants/triggers/index.ts
- src/constants/triggers/webhookHttpMethods.constants.ts
- src/locales/en/errors/translation.json
- src/locales/en/services/translation.json
- src/locales/en/tabs/translation.json
When a user creates/edits a webhook trigger, they should also have these 2 fields:
HTTP Method (selection between: GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH - upper case in the UI, but lower case in the trigger definition) - see https://docs.autokitteh.com/integrations/http/events/#event-types and https://docs.autokitteh.com/integrations/http/events#option-1-single-event-type
CEL Filter Expression - same as "filter" in other integration-based triggers - see https://docs.autokitteh.com/integrations/http/events#option-2-cel-filter-expression
Both are optional. Also, mention the option-1 and option-2 URLs as help links for users.
https://linear.app/autokitteh/issue/UI-1042/missing-ui-fields-in-webhook-trigger …
> feat(UI-1042): add missing ui fields in webhook trigger form

- src/components/organisms/editorTabs.tsx
- src/locales/en/settings/translation.json
- src/services/indexedDb.service.ts
Change the label of the AutoSave setting
https://linear.app/autokitteh/issue/UI-1121/change-the-label-of-the-autosave-setting …
> fix(UI-1121): change label for autosave setting

- src/components/organisms/triggers/table.tsx
Bug:
After the fix, the icons are looking fine in a row:
-   [ ] ☑️ (chore) - Chores - Other …
> fix(UI-1122): fix action icons in triggers table

- src/components/organisms/editorTabs.tsx
- src/components/organisms/settings/profile/profile.tsx
- src/locales/en/settings/translation.json
- src/utilities/index.ts
- src/utilities/localStorage.utils.ts
Rephrase autosave setting in user profile, change the setting label text to: "Code editing auto-save".
https://linear.app/autokitteh/issue/UI-1124/rephrase-autosave-setting-in-user-profile
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our …
> refactor(UI-1124): change auto-save label text

- src/components/organisms/editorTabs.tsx
1. prevent cmd/ctrl+s open dialog, make it save the code
2. Prevent from ctrl/cmd+z to clear the editor
https://linear.app/autokitteh/issue/UI-1120/prevent-from-ctrlcmdz-to-clear-the-editor
https://linear.app/autokitteh/issue/UI-997/prevent-cmdctrls-in-the-editor-from-opening-save-page-window
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code …
> feat: improve keyboard shortcuts handle (UI-997)(UI-1120)

- src/store/useProjectStore.ts
Fix no projects stuck on loader
https://linear.app/autokitteh/issue/UI-1134/fix-no-projects-stuck-on-loader …
> fix(UI-1134): loader stuck when no projects for user

- src/hooks/useFileOperations.ts
- src/services/indexedDb.service.ts
Bug: User cannot delete file
https://linear.app/autokitteh/issue/UI-1135/user-cannot-delete-file …
> fix(UI-1135): user cant delete files

- src/components/organisms/connections/integrations/auth0/add.tsx
- src/components/organisms/connections/integrations/auth0/edit.tsx
- src/components/organisms/connections/integrations/google/add.tsx
- src/components/organisms/connections/integrations/googlecalendar/add.tsx
- src/components/organisms/connections/integrations/googleforms/add.tsx
- src/components/organisms/connections/integrations/integrationEditForm.tsx
- src/constants/connections/integrationVariablesMapping.constants.ts
- src/constants/connections/integrationsDataKeys.constants.ts
- src/hooks/useConnectionForm.ts
- src/locales/en/integrations/translation.json
- src/validations/connection.schema.ts
- src/validations/index.ts
This is a replacement of the current "default" OAuth connection, which is not possible in Auth0. In other words, this is not a new connection type.
Based on https://github.com/autokitteh/autokitteh/pull/912:
- Connection type: "OAuth" as before
- New text fields (all are required):
- ---Client ID
- ---Client Secret
- ---Auth0 Domain
- The "Start OAuth Flow" button should remain the same
- Help link:
- ---Label: "AutoKitteh guide: configuring Auth0 connections"
- ---URL: https://docs.autokitteh.com/integrations/auth0/config/
https://linear.app/autokitteh/issue/UI-1138/update-connection-ui-for-auth0
-   [ ] 🐞 …
> feat(UI-1138): update auth0 connection setup

- src/app.tsx
- src/components/organisms/settings/organization/deleteOrganizationModal.tsx
- src/components/organisms/settings/organization/index.ts
- src/components/organisms/settings/organization/newOrganization.tsx
- src/components/organisms/settings/organization/organization.tsx
- src/constants/forms/formSelectInput.constants.ts
- src/enums/components/modal.enum.ts
- src/locales/en/settings/translation.json
- src/validations/coseAndAssets.schema.ts
- src/validations/index.ts
- src/validations/manualRun.schema.ts
- src/validations/organization.schema.ts
- src/validations/shared.schema.ts
- src/validations/trigger.schema.ts
Create Organization Settings page
https://linear.app/autokitteh/issue/UI-1063/create-organization-settings-page …
> feat(UI-1063): add organization settings page

- src/constants/triggers/webhookHttpMethods.constants.ts
-   [ ] ☑️ (chore) - Chores - Other changes that don't modify src or test files
-   [ ] ↩️ …
> fix(UI-1136): in webhook trigger user cant change http method back to any

- src/components/organisms/connections/integrations/auth0/edit.tsx
- src/utilities/index.ts
- src/utilities/validateUrl.utils.ts
- src/validations/connection.schema.ts
URL should be like this: dev-xyz.us.auth0.com without http or https.
https://linear.app/autokitteh/issue/UI-1145/fix-auth0-url-validation …
> fix(ENG-1930): fix url validation in auth0 connection

- src/components/organisms/editorTabs.tsx
- src/components/organisms/splitFrame.tsx
- src/enums/storeName.enum.ts
- src/interfaces/store/index.ts
- src/interfaces/store/sharedBetweenProjectsStore.interface.ts
- src/store/index.ts
- src/store/useSharedBetweenProjectsStore.ts
When we move between projects, keep the same location in the file when we return.
Demonstration:
On the first project, we left the cursor on line 39
On the second one on line 48
On the third project,t we focused on the 35th line
On the last and the fourth project we focused on the 24th line
When we moving back to the previous projects, we can see that the editor open the files on the same line we left the cursor:
https://github.com/user-attachments/assets/05611c61-9a75-40fc-8a4d-02618de4c3c3
https://linear.app/autokitteh/issue/UI-1046/return-to-the-same-scrolled-location-in-editor-file-moving-between
-   [ ] 🐞 …
> feat(UI-1046): return cursor to the same point in the code moving between projects

- src/assets/index.css
- src/components/organisms/deployments/sessions/tabs/outputs.tsx
**Expected behavior**
Ideally, you should see a long line with 100 characters (10 times of 123456789x).
But we can't assume that the user sees the entire log view, or that they know their log lines are being cut.
We need to know exactly what's the visible area, and if characters are hidden, at least show a horizontal scroll bar - so the user could do something (increase the size of the right panel, or enrage the whole window).
Here's what I see in a 1440x900 window: 56 characters out of the 100
Here's what I see in a 1920x1080 window: 88 characters
https://linear.app/autokitteh/issue/UI-1137/session-log-is-cut-on-the-right-side-because-the-page-doesnt-know-its
> refactor(UI-1137): enhance scrollbar visibility in outputs component

- src/components/organisms/dashboard/projectsTable.tsx
1. The count of stopped not displayed
2. The number of created not displayed
https://linear.app/autokitteh/issue/UI-1146/fix-main-projects-table …
> fix(UI-1146): fix information in main projects table

- src/components/organisms/editorTabs.tsx
Keyboard shortcuts like cmd+r doesn't work.
https://linear.app/autokitteh/issue/UI-1149/fix-keyboards-events-on-page
> fix(UI-1149): fix keyboard shortcuts

- src/components/templates/descopeMiddleware.tsx
- src/constants/googleTagManager.constats.ts
- src/constants/index.ts
- src/interfaces/store/userStore.interface.ts
- src/store/useUserStore.ts
- src/types/index.ts
- src/utilities/gTag.utils.ts
- src/utilities/index.ts
Marketing. Track login events.
https://linear.app/autokitteh/issue/UI-1141/marketing-gtag-add-login-event
> feat(UI-1141): gtag - add login event

- e2e/project/trigger.spec.ts
An outcome of [ENG-1929](https://linear.app/autokitteh/issue/ENG-1929/user-cant-delete-scheduler-trigger) 
After fixed, return the test, that is skipped at this moment.
https://linear.app/autokitteh/issue/UI-1144/remove-skip-from-delete-scheduler-trigger-test
> test(UI-1144): return scheduler trigger e2e test

- e2e/fixtures.ts
- e2e/pages/dashboard.ts
- e2e/pages/index.ts
- e2e/pages/project.ts
- e2e/project/webhookSessionTriggered.spec.ts
- src/components/organisms/topbar/project/buttons.tsx
- src/locales/en/projects/translation.json
- src/store/useProjectStore.ts
> test(UI-1148): project deletion in e2e tests

- netlify.toml
In order to avoid these warnings, refactor the configuration file:
https://uploads.linear.app/f7061cec-0368-406e-8171-dce5a6eec43a/3c758b19-ddde-4377-b0f7-36c344399024/44478f90-b23f-48d7-8adb-c664f2869705
https://linear.app/autokitteh/issue/UI-1154/fix-build-in-netlify
> fix(UI-1154): fix build run on netlify

- src/components/organisms/dashboard/projectsTable.tsx
- src/components/organisms/introMainBlock.tsx
- src/components/organisms/shared/index.ts
- src/components/organisms/shared/socials.tsx
- src/components/pages/dashboard.tsx
- src/constants/dashboard.constants.ts
- src/constants/index.ts
- src/locales/en/dashboard/translation.json
- src/locales/en/index.ts
- src/locales/en/shared/translation.json
Projects table - remove "Start New Project / From Template" & Add socials
1. Remove "Start New Project" Button
2. Remove "or Start From Template"
Add socials like we have in the intro/welcome page:
The screen after the changes:
1440px:
1980px:
2K:
Mobile:
https://linear.app/autokitteh/issue/UI-1117/projects-table-remove-start-new-project-from-template-and-add-socials
-   [ ] 🎨 …
> feat(UI-1117): projects table remove 'new project' add 'socials'

- index.html
Marketing - Add HubSpot form submission on login success
https://linear.app/autokitteh/issue/UI-1142/marketing-add-hubspot-form-submission-on-login-success
> feat(UI-11423): optimize hubspot integration - add missing script

- src/app.tsx
Hide this native feedback widget of sentry:
https://linear.app/autokitteh/issue/UI-1163/hide-native-feedback-widget-of-sentry
> fix(UI-1163): hide native sentry feedback button

- e2e/project/topbar.spec.ts
- e2e/project/webhookSessionTriggered.spec.ts
- src/app.tsx
- src/components/organisms/dashboard/projectsTable.tsx
- src/components/organisms/deployments/sessionStats.tsx
- src/components/organisms/deployments/sessions/filter.tsx
- src/components/organisms/deployments/sessions/table.tsx
- src/components/organisms/deployments/sessions/tableList.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/components/organisms/deployments/tableContent.tsx
- src/components/organisms/topbar/project/navigation.tsx
- src/components/pages/index.ts
- src/components/pages/sessions.tsx
- src/hooks/useLastVisitedEntity.ts
- src/interfaces/components/session.interface.ts
- src/interfaces/store/projectStore.interface.ts
- src/services/sessions.service.ts
- src/store/useProjectStore.ts
- src/utilities/calculateDeploymentSessionsStats.utils.ts
- src/utilities/deploymentsSessionStats.utils.ts
- src/utilities/getSessionStateColor.utils.ts
- src/utilities/index.ts
Projects table - go to sessions with filter
Design:
https://www.figma.com/design/klCZL68fUd6pw0DEu0Sj7f/Autokitteh%3A-Look-%26-Feel-design-versions?node-id=3928-137507&t=31hb8QH7NQQPEC90-4
https://linear.app/autokitteh/issue/UI-1130/projects-table-go-to-sessions-with-filter
> feat(UI-1130): add sessions filter from home projects table

- src/components/organisms/sidebar/userMenu.tsx
- src/components/templates/settingsLayout.tsx
Display system log in settings
https://linear.app/autokitteh/issue/UI-1172/display-sistem-log-in-organizations-settings
> fix(UI-1172): display system log in settings

- src/app.tsx
- src/components/organisms/settings/organization/addOrganization.tsx
- src/components/organisms/settings/organization/index.ts
- src/components/organisms/settings/organization/organization.tsx
- src/components/organisms/settings/organization/organizationCreatedModal.tsx
- src/components/templates/descopeMiddleware.tsx
- src/enums/components/menu.enum.ts
- src/enums/storeName.enum.ts
- src/interfaces/store/index.ts
- src/interfaces/store/organizationStore.interface.ts
- src/locales/en/settings/translation.json
- src/store/index.ts
- src/store/useOrganizationStore.ts
- src/validations/index.ts
- src/validations/organization.schema.ts
Add organizations' initial functionality.
https://linear.app/autokitteh/issue/UI-1167/functionality-user-login-and-fetch-orgs-for-the-menu
> feat(UI-1167): organizations fetching and management

- src/hooks/useCreateProjectFromTemplate.tsx
- src/hooks/useFileOperations.ts
> fix(UI-1177): quick start project creation with files

- src/components/organisms/modals/importProjectModal.tsx
- src/components/organisms/topbar/dashboard.tsx
- src/hooks/useProjectActions.tsx
https://linear.app/autokitteh/issue/UI-1179/optimize-file-creation
> refactor(UI-1179): optimize project creation

- src/interfaces/store/organizationStore.interface.ts
- src/interfaces/store/userStore.interface.ts
- src/mainApp.tsx
- src/models/project.model.ts
- src/services/projects.service.ts
- src/store/useOrganizationStore.ts
- src/store/useProjectStore.ts
- src/store/useUserStore.ts
- src/types/models/project.type.ts
> feat(UI-1178): filter all relevant requests by filter id

- src/components/molecules/copyButton.tsx
- src/components/molecules/idCopyButton.tsx
- src/components/molecules/toast.tsx
- src/components/organisms/connections/table.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/components/organisms/deployments/tableContent.tsx
- src/components/organisms/events/table/row.tsx
- src/components/organisms/events/viewer.tsx
- src/components/organisms/settings/clientConfiguration.tsx
- src/components/organisms/topbar/project/projectName.tsx
- src/components/organisms/triggers/formParts/webhook.tsx
- src/components/organisms/triggers/table/popoverContent.tsx
- src/constants/namespaces.logger.constants.ts
- src/interfaces/components/toast.interface.ts
- src/locales/en/components/buttons/translation.json
Make idCopyButton icon (1) smaller like (2)
Like projectId copy icon:
https://linear.app/autokitteh/issue/UI-1176/reduce-copy-icon-size
> refactor(UI-1176): reduce copy icon size

- src/components/templates/descopeMiddleware.tsx
https://linear.app/autokitteh/issue/UI-1199/on-refresh-the-user-logs-out
> fix(UI-1199): fix login

- src/app.tsx
- src/components/atoms/index.ts
- src/components/atoms/input.tsx
- src/components/atoms/successMessage.tsx
- src/components/organisms/settings/organization/settings.tsx
- src/components/organisms/settings/user/organizations/table.tsx
- src/components/organisms/settings/user/profile.tsx
- src/components/organisms/sidebar/userMenu.tsx
- src/interfaces/components/forms/input.interface.ts
- src/locales/en/global/translation.json
- src/locales/en/services/translation.json
- src/locales/en/settings/translation.json
- src/locales/en/stores/translation.json
- src/models/user.model.ts
- src/models/utils/userStatusConverter.utils.ts
- src/services/organizations.service.ts
- src/services/users.service.ts
- src/store/useOrganizationStore.ts
- src/types/index.ts
- src/types/models/organization.type.ts
- src/types/stores/organizationsStore.types.ts
- src/types/theme.type.ts
Allow users rename their displayName
https://linear.app/autokitteh/issue/UI-1208/allow-users-rename-their-displayname
> feat(UI-1208): allow users rename their display-name

- src/components/organisms/topbar/project/buttons.tsx
- src/hooks/useProjectActions.tsx
Delete project with error shouldn't redirect to the homepage.
When we:
1. Go to the project page
2. Make sure you have an active deployment
3. Try to delete the project
Expected Result:
1. Display error
2. Keep you on the project page
Actual Result:
1. Display error
2. Redirected to the homepage
https://linear.app/autokitteh/issue/UI-1216/delete-project-with-error-shouldnt-redirect-to-the-homepage
> fix(UI-1216): project delete with error shouldn't redirect to homepage

- src/components/templates/settingsLayout.tsx
- src/components/templates/systemLogLayout.tsx
Page to big - causes horizontal scroll:
Page to small:
https://linear.app/autokitteh/issue/UI-1233/design-issues
> fix(UI-1233): design issues

- src/components/organisms/topbar/project/projectConfig.tsx
- src/components/templates/systemLogLayout.tsx
Page to big - causes horizontal scroll:
https://linear.app/autokitteh/issue/UI-1233/design-issues
> fix(UI-1233): fix horizontal scroll for home and intro page

- src/components/organisms/triggers/add.tsx
- src/components/organisms/triggers/edit.tsx
- src/constants/forms/formSelectInput.constants.ts
- src/constants/forms/index.ts
- src/store/useManualRunStore.ts
- src/types/startSessionArgs.type.ts
Fix jsonInputs decoding when session start
https://linear.app/autokitteh/issue/UI-1263/fix-jsoninputs-decoding-when-session-start
> fix(UI-1263): fix json inputs format on session start

- src/store/useManualRunStore.ts
Fix deconstruct Entrypoint for Manual Run
https://linear.app/autokitteh/issue/UI-1262/fix-deconstruct-entrypoint-for-manual-run
> fix(UI-1262): fix entrypoint deconstruction for manual run

- src/components/organisms/topbar/project/buttons.tsx
- src/store/cache/useCacheStore.ts
**Deployments list fetch loop in the sessions screen**
In some cases, we are getting re-render loop in the sessions screen because the new sessions filter trying to get the latest list of deployments, and when he get it - he asks for it again in an infinite loop. 
To make the bug even clearer, it happens when the user goes to the sessions filtered from the homepage, for example by clicking on the green sessions counter in the completed sessions column in the projects table.
Example:
https://github.com/user-attachments/assets/4308168f-fc2d-4622-bc29-8339cbb86506
https://linear.app/autokitteh/issue/UI-1265/deployments-list-fetch-loop-in-the-sessions-screen
> fix(UI-1265): fix re-fetch deployments list loop in the sessions screen

- src/services/sessions.service.ts
Basically it means simply add 2 params to the request terminate and terminationDelay
https://linear.app/autokitteh/issue/UI-1267/stop-sessions-hard-stop
> fix(UI-1267): add termination options to stop session method

- src/store/useManualRunStore.ts
https://linear.app/autokitteh/issue/UI-1296/session-manual-run-reduce-one-stringify
> fix(UI-1296): session manual run fix

- src/constants/connections/integrationsCustomOAuthPaths.ts
- src/hooks/useConnectionForm.ts
Fix other customOauth connections (like google connections)
Currently, we are getting undefined in the URL:
> fix(UI-1297): fix custom oauth connections

- src/components/organisms/dashboard/projectsTable.tsx
- src/components/organisms/dashboard/projectsTableHeader.tsx
- src/components/organisms/dashboard/projectsTableRow.tsx
- src/components/organisms/modals/deleteActiveDeploymentProjectModal.tsx
- src/components/organisms/modals/deleteDrainingDeploymentProjectModal.tsx
- src/components/organisms/modals/deleteProjectModal.tsx
- src/components/organisms/modals/index.ts
- src/components/organisms/topbar/project/buttons.tsx
- src/enums/components/modal.enum.ts
- src/hooks/useProjectActions.tsx
- src/interfaces/components/dashboard.interface.ts
- src/interfaces/components/index.ts
- src/interfaces/components/welcomePageCard.interface.ts
- src/locales/en/dashboard/translation.json
- src/locales/en/deployments/translation.json
- src/locales/en/modals/translation.json
- src/locales/en/projects/translation.json
- src/store/useProjectStore.ts
- src/types/models/project.type.ts
Add action icon to the projects table near the export icon (if the project is active):
https://linear.app/autokitteh/issue/UI-1231/ability-to-stop-active-deployment-from-the-homepage-projects-table
> feat(UI-1231, UI-1269): add ability to stop active deployment

- src/app.tsx
- src/components/molecules/index.ts
- src/components/molecules/templateIntegrationsIcons.tsx
- src/components/organisms/dashboard/templates/tabs/card.tsx
- src/components/organisms/index.ts
- src/components/organisms/templateStart.tsx
- src/components/pages/index.ts
- src/components/pages/templateLanding.tsx
- src/components/templates/appLayout.tsx
- src/components/templates/systemLogLayout.tsx
- src/interfaces/store/templates.interface.ts
- src/locales/en/dashboard/translation.json
- src/locales/en/templates/translation.json
Create a page that contains information about a template the template name should be taken from the URL query params
https://linear.app/autokitteh/issue/UI-1291/template-landing-page
> feat(UI-1291): add template landing page

- src/global.d.ts
- src/types/index.ts
- src/utilities/gTag.utils.ts
fix the google tag manager script
https://linear.app/autokitteh/issue/UI-1316/gtm
> fix(UI-1316): gtm

- src/components/organisms/editorTabs.tsx
- src/components/organisms/templateStart.tsx
- src/components/pages/templateLanding.tsx
- src/constants/index.ts
- src/constants/project.constants.ts
- src/hooks/useCreateProjectFromTemplate.tsx
- src/hooks/useProjectActions.tsx
> feat(UI-1291): add opening README.md with markdown and set default opened project file

- src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
> fix(UI-1322): manual run json structure

- src/components/organisms/connections/integrations/integrationEditForm.tsx
Connections opening OAuth modal on non-OAuth connection type
https://linear.app/autokitteh/issue/UI-1324/connections-opening-oauth-modal-on-non-oauth-connection-type
> fix(UI-1324): fix connection type check on edit submit

- eslint.config.mjs
- src/components/atoms/tooltip.tsx
- src/components/molecules/menu/menu.tsx
- src/components/organisms/deployments/sessions/table/table.tsx
- src/components/organisms/sidebar/sidebar.tsx
- src/components/templates/settingsLayout.tsx
- src/interfaces/components/tooltip.interface.ts
Add tooltip  to sidebar menu
https://linear.app/autokitteh/issue/UI-1313/menu-hover-with-name-tootlip
> feat(UI-1313): add tooltip to sidebar menu items

- src/components/molecules/menu/menu.tsx
- src/components/templates/descopeMiddleware.tsx
> fix(UI-1326): add templates path to allowed in our router

- src/components/atoms/input.tsx
- src/components/atoms/tooltip.tsx
- src/components/organisms/topbar/project/manualRun/manualRunParamsForm.tsx
- src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
- src/interfaces/components/tooltip.interface.ts
- src/interfaces/store/manualRunStore.interface.ts
- src/locales/en/deployments/translation.json
- src/services/sessions.service.ts
- src/store/useManualRunStore.ts
- src/types/index.ts
- src/types/manualRunParams.type.ts
- src/validations/manualRun.schema.ts
> fix(UI-1363): fix the manual run feature after recent refactor and backend change

- src/services/events.service.ts
- src/store/cache/useCacheStore.ts
Add param orgID for events.list
https://linear.app/autokitteh/issue/UI-1293/events-list-by-orgid
> feat(UI-1293): add orgId parameter to events list

- src/components/organisms/connections/integrations/github/add.tsx
- src/components/organisms/connections/integrations/github/edit.tsx
- src/components/organisms/connections/integrations/slack/add.tsx
- src/components/organisms/connections/integrations/slack/edit.tsx
- src/constants/connections/formsPerIntegrationsMapping.constants.ts
- src/constants/featureFlags.constants.ts
- src/constants/lists/connections/options.constants.ts
- src/hooks/useConnectionForm.ts
- src/vite-env.d.ts
- vite.config.ts
Add ability to handle legacy authentication types for GitHub and Slack.
https://linear.app/autokitteh/issue/UI-1357/default-app-backward-compatibility
https://linear.app/autokitteh/issue/UI-1355/default-app-backward-compatibility
> feat: enable slack and github backward compatibility (UI-1355)(UI-1357)

- src/components/organisms/settings/user/organizations/table.tsx
- src/locales/en/settings/translation.json
- src/locales/en/stores/translation.json
- src/store/useOrganizationStore.ts
fix infinite loading in user organizations screen
https://linear.app/autokitteh/issue/UI-1368/fix-infinite-loading-in-user-organizations-screen
> fix(UI-1368): fix infinite loading in user organizations screen

- src/components/templates/descopeMiddleware.tsx
- src/constants/global.constants.ts
- src/constants/index.ts
- src/vite-env.d.ts
- vite.config.ts
> fix: hubspot tracker

- src/components/organisms/settings/organization/switchOrganization.tsx
- src/components/organisms/settings/user/organizations/table.tsx
- src/components/organisms/sidebar/sidebar.tsx
- src/components/organisms/sidebar/userMenu.tsx
- src/locales/en/sidebar/translation.json
- src/store/useOrganizationStore.ts
- src/types/stores/organizationsStore.types.ts
> fix: user menu organizations flickering

- src/components/organisms/connections/integrations/confluence/add.tsx
- src/components/organisms/connections/integrations/github/add.tsx
- src/components/organisms/connections/integrations/hubspot/add.tsx
- src/components/organisms/connections/integrations/hubspot/edit.tsx
- src/components/organisms/connections/integrations/integrationEditForm.tsx
- src/components/organisms/connections/integrations/jira/add.tsx
- src/components/organisms/connections/integrations/slack/add.tsx
- src/components/organisms/connections/integrations/slack/authMethods/index.ts
- src/components/organisms/connections/integrations/slack/authMethods/oauthPrivate.tsx
- src/components/organisms/connections/integrations/slack/edit.tsx
- src/constants/connections/formsPerIntegrationsMapping.constants.ts
- src/constants/connections/integrationsCustomOAuthPaths.ts
- src/constants/connections/integrationsDataKeys.constants.ts
- src/constants/lists/connections/options.constants.ts
- src/enums/components/connection.enum.ts
- src/enums/components/index.ts
- src/hooks/useConnectionForm.ts
- src/locales/en/integrations/translation.json
- src/validations/connection.schema.ts
- src/validations/index.ts
https://linear.app/autokitteh/issue/UI-1347/slack
> feat(UI-1347)(UI-1356): add support for private OAuth slack

- src/components/templates/descopeMiddleware.tsx
- src/store/useOrganizationStore.ts
- src/types/stores/organizationsStore.types.ts
> fix: organizations on clean login

- src/components/organisms/connections/integrations/github/authMethods/oauthPrivate.tsx
- src/components/organisms/connections/integrations/height/add.tsx
- src/components/organisms/connections/integrations/height/authMethods/apiKey.tsx
- src/components/organisms/connections/integrations/height/authMethods/index.ts
- src/components/organisms/connections/integrations/height/authMethods/oauth.tsx
- src/components/organisms/connections/integrations/height/authMethods/oauthPrivate.tsx
- src/components/organisms/connections/integrations/height/edit.tsx
- src/components/organisms/connections/integrations/slack/authMethods/oauthPrivate.tsx
- src/constants/connections/formsPerIntegrationsMapping.constants.ts
- src/constants/connections/integrationVariablesMapping.constants.ts
- src/constants/connections/integrationsCustomOAuthPaths.ts
- src/constants/connections/integrationsDataKeys.constants.ts
- src/constants/featureFlags.constants.ts
- src/constants/lists/connections/index.ts
- src/constants/lists/connections/options.constants.ts
- src/enums/components/connection.enum.ts
- src/hooks/useConnectionForm.ts
- src/locales/en/integrations/translation.json
- src/validations/connection.schema.ts
- src/validations/index.ts
- src/vite-env.d.ts
- vite.config.ts
Add Private app, Api Key integrations and refactor code
https://linear.app/autokitteh/issue/UI-1351/api-key
https://linear.app/autokitteh/issue/UI-1350/private-app
https://linear.app/autokitteh/issue/UI-1341/linear
> feat: add Height integration with OAuth and API key support (UI-1345)(UI-1351)(UI-1350)

- src/components/organisms/connections/integrations/linear/add.tsx
- src/components/organisms/connections/integrations/linear/authMethods/apiKey.tsx
- src/components/organisms/connections/integrations/linear/authMethods/index.ts
- src/components/organisms/connections/integrations/linear/authMethods/oauth.tsx
- src/components/organisms/connections/integrations/linear/authMethods/oauthPrivate.tsx
- src/components/organisms/connections/integrations/linear/edit.tsx
- src/constants/connections/formsPerIntegrationsMapping.constants.ts
- src/constants/connections/integrationVariablesMapping.constants.ts
- src/constants/connections/integrationsCustomOAuthPaths.ts
- src/constants/connections/integrationsDataKeys.constants.ts
- src/constants/featureFlags.constants.ts
- src/constants/lists/connections/index.ts
- src/constants/lists/connections/options.constants.ts
- src/enums/components/connection.enum.ts
- src/hooks/useConnectionForm.ts
- src/locales/en/integrations/translation.json
- src/validations/connection.schema.ts
- src/validations/index.ts
- src/vite-env.d.ts
- vite.config.ts
https://linear.app/autokitteh/issue/UI-1341/linear
https://linear.app/autokitteh/issue/UI-1343/private-app
https://linear.app/autokitteh/issue/UI-1344/api-key
> feat: add Linear integration Private OAuth and API key support (UI-1341)(UI-1343)(UI-1344)

- src/constants/featureFlags.constants.ts
- src/constants/lists/connections/options.constants.ts
- src/vite-env.d.ts
- vite.config.ts
Convert Connections flags from DISPLAY to HIDE
https://linear.app/autokitteh/issue/UI-1375/convert-connections-flags-from-show-to-hide
> refactor(UI-1375): update feature flags name

- index.html
- src/components/templates/descopeMiddleware.tsx
- src/constants/global.constants.ts
- src/constants/index.ts
- src/vite-env.d.ts
- vite.config.ts
> fix(UI-1378): fix hubspot integration on login

- src/components/organisms/connections/integrations/integrationEditForm.tsx
> fix(UI-1386): fix private oauth edit

- src/components/organisms/topbar/project/manualRun/manualRunParamsForm.tsx
- src/components/organisms/topbar/project/manualRun/manualRunSettingsDrawer.tsx
- src/interfaces/store/manualRunStore.interface.ts
- src/locales/en/deployments/translation.json
- src/store/useManualRunStore.ts
- src/validations/index.ts
- src/validations/manualRun.schema.ts
> fix(UI-1381): fix manual run

- src/components/organisms/editorTabs.tsx
- src/store/useSharedBetweenProjectsStore.ts
Fix cursor position after change or remove content
https://linear.app/autokitteh/issue/UI-1383/after-auto-save-cursor-jumps
> refactor(UI-1383): improve cursor position handling

- src/components/organisms/connections/integrations/zoom/add.tsx
- src/components/organisms/connections/integrations/zoom/authMethods/index.ts
- src/components/organisms/connections/integrations/zoom/authMethods/oauth.tsx
- src/components/organisms/connections/integrations/zoom/authMethods/oauthPrivate.tsx
- src/components/organisms/connections/integrations/zoom/authMethods/serverToServer.tsx
- src/components/organisms/connections/integrations/zoom/edit.tsx
- src/constants/connections/formsPerIntegrationsMapping.constants.ts
- src/constants/connections/integrationVariablesMapping.constants.ts
- src/constants/connections/integrationsCustomOAuthPaths.ts
- src/constants/connections/integrationsDataKeys.constants.ts
- src/constants/featureFlags.constants.ts
- src/constants/lists/connections/index.ts
- src/constants/lists/connections/options.constants.ts
- src/enums/components/connection.enum.ts
- src/enums/connections/connectionTypes.enum.ts
- src/locales/en/integrations/translation.json
- src/validations/connection.schema.ts
- src/validations/index.ts
- src/vite-env.d.ts
- vite.config.ts
https://linear.app/autokitteh/issue/UI-1346/zoom
https://linear.app/autokitteh/issue/UI-1353/private-app
https://linear.app/autokitteh/issue/UI-1354/server-to-server
> feat: Zoom add Private OAuth and ServerToServer auth types (UI-1346)(UI-1353)(UI-1354)

- src/components/organisms/deployments/sessions/viewer.tsx
- src/store/cache/useOutputsCacheStore.ts
- src/utilities/copyToClipboard.utils.ts
**Consider latest state in logs copy/download:**
1. Add the last print from the last state in logs to the copy/download
2. In case we have no logs to download, stop the loader:
https://linear.app/autokitteh/issue/UI-1387/consider-latest-state-in-logs-copydownload
> fix(UI-1387): fix logs copy and download

- src/constants/events.constants.ts
> feat(UI-1389): reduce amount of the events we fetch to display

- src/components/organisms/connections/integrations/slack/add.tsx
Slack OAuth Pop-Up doesn't open
https://linear.app/autokitteh/issue/UI-1390/slack-oauth-pop-up-doesnt-open
> fix(UI-1390): slack oauth doesn't open

- src/store/useTemplatesStore.ts
reload templates from kittehub when there are changes
https://linear.app/autokitteh/issue/UI-1392/reload-templates-when-there-are-changes-in-kittehub-repository
> fix(UI-1392): reload templates from kittehub when there are changes

- src/components/organisms/modals/deleteActiveDeploymentProjectModal.tsx
- src/locales/en/modals/translation.json
We need to highlight somehow that when the user deletes a project with an active deployment, it will have coincidences.
https://linear.app/autokitteh/issue/UI-1401/add-warning-sing-in-project-deletion-modal
> fix(UI-1401): update deletion warning messages for active deployments

- package-lock.json
- package.json
- vite.config.ts
Enable running local frontend on a remote backend
https://linear.app/autokitteh/issue/UI-1409/enable-running-local-frontend-on-a-remote-backend
> feat(UI-1409): run local frontend on remote backend

- index.html
- src/vite-env.d.ts
- vite.config.ts
Add LuckyOrange tool
https://linear.app/autokitteh/issue/UI-1416/add-lucky-orange
> feat(UI-1416): add lucky orange ux tool

- src/hooks/useConnectionForm.ts
> fix: fix missing integration name in private oauth creation url

- src/components/organisms/dashboard/templates/tabs/card.tsx
- src/components/organisms/dashboard/templates/tabs/createModal.tsx
- src/components/organisms/triggers/edit.tsx
- src/components/templates/descopeMiddleware.tsx
- src/constants/featureFlags.constants.ts
- src/vite-env.d.ts
- vite.config.ts
The description should be aligned to the left:
> feat(UI-1405): fix templates description

- index.html
https://linear.app/autokitteh/issue/UI-1419/fix-lucky-orange-view
> fix(UI-1419): fix lucky orange tracker

- src/components/molecules/accordion.tsx
When we create a project from a template and click on the additional info, it submits the form and creates the project. To fix it, we need to stop the accordion click propagation.
https://linear.app/autokitteh/issue/UI-1424/fix-accordion-click-propogation
> fix(UI-1424): fix accordion click propogation

- src/components/molecules/welcomeCard.tsx
fix loader in the welcome screen buttons
https://linear.app/autokitteh/issue/UI-1421/align-in-progress-mode-in-onboarding-card
> fix(UI-1421): fix loader in the welcome screen buttons

- src/components/atoms/buttons/button.tsx
- src/components/atoms/typography.tsx
- src/components/organisms/settings/user/profile.tsx
- src/interfaces/components/button.interface.ts
- src/locales/en/settings/translation.json
https://linear.app/autokitteh/issue/UI-1420/lucky-orange-cookie-consent
> feat(UI-1420): lucky orange cookie consent

- src/components/organisms/connections/integrations/salesforce/add.tsx
- src/components/organisms/connections/integrations/salesforce/authMethods/index.ts
- src/components/organisms/connections/integrations/salesforce/authMethods/oauth.tsx
- src/components/organisms/connections/integrations/salesforce/authMethods/oauthPrivate.tsx
- src/components/organisms/connections/integrations/salesforce/edit.tsx
- src/constants/connections/formsPerIntegrationsMapping.constants.ts
- src/constants/connections/integrationsCustomOAuthPaths.ts
- src/constants/featureFlags.constants.ts
- src/constants/lists/connections/index.ts
- src/constants/lists/connections/options.constants.ts
- src/validations/connection.schema.ts
- src/validations/index.ts
- src/vite-env.d.ts
- vite.config.ts
Add Default OAuth connection type to Salesforce integration.
https://linear.app/autokitteh/issue/UI-1429/salesforce-default-oauth
> feat(UI-1429): add default-oauth to salesforce integration

- src/constants/connections/integrationVariablesMapping.constants.ts
> fix(UI-1429): fix default-oauth to salesforce integration edit

- src/interfaces/store/templates.interface.ts
- src/store/useTemplatesStore.ts
Refactor github templates fetch var names to make the code clearer.
https://linear.app/autokitteh/issue/UI-1444/refactor-github-templates-fetch-var-names
> refactor(UI-1444): improve templates update var names

- src/components/atoms/buttons/button.tsx
Manual Run - don't submit form on cancel
https://linear.app/autokitteh/issue/UI-1445/manual-run-dont-submit-form-on-cancel
> fix(UI-1445): fix all buttons became submit type

- src/api/grpc/transport.grpc.api.ts
The user sees the new page with the selection between the quickstart and other templates, and a couple of errors in the bottom-right corner (because the credentials are wrong).
The user needs to manually reload the page in order to get to the sign-in page.
https://linear.app/autokitteh/issue/UI-1432/load-the-cloud-homepage
> fix(UI-1432): fix PermissionDenied error in authInterceptor

- src/components/molecules/index.ts
- src/components/molecules/loadingOverlay.tsx
- src/components/organisms/dashboard/templates/catalog.tsx
- src/components/organisms/templateStart.tsx
- src/components/organisms/welcome.tsx
- src/components/pages/templateLanding.tsx
- src/components/templates/descopeMiddleware.tsx
- src/store/useTemplatesStore.ts
> feat(UI-1449): templates loading overlay

- src/components/organisms/settings/organization/switchOrganization.tsx
After switch organization, system log will be clear
https://linear.app/autokitteh/issue/UI-1453/switch-organization-reset-system-log
> feat(UI-1453): clear logs after organization switch

- src/components/organisms/connections/table.tsx
if warning - link to edit + edit icon green
https://linear.app/autokitteh/issue/UI-1436/connections-table-actions
> feat(UI-1436): update connection status display and button style

- src/components/templates/descopeMiddleware.tsx
- src/constants/global.constants.ts
- src/constants/index.ts
- src/locales/en/login/translation.json
- src/locales/en/stores/translation.json
- src/store/useOrganizationStore.ts
- src/types/stores/organizationsStore.types.ts
- src/utilities/index.ts
- src/utilities/requiresRefresh.utils.ts
- src/utilities/retry.utils.ts
- vite.config.ts
> feat(UI-1452): refresh cookie each 24 hours

- src/components/organisms/connections/table.tsx
- src/hooks/useConnectionForm.ts
- src/store/useConnectionStore.ts
Add connections checker to all connections
https://linear.app/autokitteh/issue/UI-1414/add-connections-checker-to-all-connections
> feat(UI-1414): add connection in progress state and improve status checking

- src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
- src/interfaces/models/session.interface.ts
- src/models/activity.model.ts
Fix Return Values Crash
https://linear.app/autokitteh/issue/UI-1384/fix-execution-flow
> fix(UI-1384): fix execution flow return values

- src/hooks/useVirtualizedList.tsx
- src/interfaces/store/activitiesAndOutputsCache.store.interface.ts
- src/store/cache/useActivitiesCacheStore.ts
- src/store/cache/useOutputsCacheStore.ts
> fix(UI-1463): fix missing last state print in session outputs

- src/assets/index.css
- src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
- src/interfaces/models/session.interface.ts
- src/models/activity.model.ts
- src/utilities/pythonStringToJson.utils.ts
Fix display correct args and kwargs
https://linear.app/autokitteh/issue/UI-1431/fix-display-correct-args-and-kwargs
> fix(UI-1431): improve kwargs handling and error parsing in activity model

- src/components/organisms/connections/table.tsx
> feat(UI-1466): fix connection init button

- src/interfaces/store/templates.interface.ts
- src/store/useTemplatesStore.ts
- src/store/useTourStore.ts
> fix(UI-1481): fix templates and tours loader

- src/components/organisms/deployments/sessions/table/table.tsx
Sometimes, when clicking on the sessions, we get 404, should fix It
https://linear.app/autokitteh/issue/UI-1480/getting-404-after-session-fails
> fix(UI-1480): improve navigation

- src/components/molecules/toursProgressStepper.tsx
- src/components/organisms/dashboard/templates/catalog.tsx
- src/components/organisms/welcome.tsx
- src/components/pages/intro.tsx
- src/components/pages/templateLanding.tsx
- src/components/templates/appProvider.tsx
- src/services/indexedDB/indexedDb.service.ts
We have this issue, the templates are not correctly loading.
https://github.com/user-attachments/assets/4ca7aa3d-d607-481b-a3c9-27609bfac9a6
https://linear.app/autokitteh/issue/UI-1484/fix-templates-infinite-loader
> feat(UI-1484): fix templates infinite loader

- src/hooks/useVirtualizedList.tsx
> fix(UI-1487): fix session outputs scrolling

- e2e/pages/dashboard.ts
- src/assets/new_project_program/program.py
> fix: s/hello world/meow, world!/

- src/store/useOrganizationStore.ts
> fix: safely access current organization in useOrganizationStore

- src/components/organisms/connections/integrations/linear/add.tsx
- src/components/organisms/connections/integrations/linear/edit.tsx
- src/constants/connections/integrationVariablesMapping.constants.ts
- src/constants/connections/integrationsDataKeys.constants.ts
- src/constants/lists/connections/options.constants.ts
- src/hooks/useConnectionForm.ts
- src/utilities/setFormValues.utils.ts
- src/validations/connection.schema.ts
- src/validations/index.ts
Fix the problem that the actor selector is not being sent when we sending the "Add connection" form to the backend.
https://linear.app/autokitteh/issue/UI-1499/actor-selection-not-passed-in-linear-connection-addition
> fix((UI-1499): linear actor not sent to the backend

- src/components/templates/systemLogLayout.tsx
> fix(UI-1494): ai chatbot - remove button in project

- src/hooks/useChatbotIframe.ts
> feat(UI-1494): fix credentials

- src/components/organisms/connections/integrations/integrationEditForm.tsx
After connection was created - when we were changing the actor in edit page - it wasn't saving.
> fix: fix linear integration edit (actor change)

- src/components/organisms/deployments/sessions/activities-chart/executionFlowChart.tsx
- src/components/organisms/deployments/sessions/tabs/activities/infiniteList.tsx
- src/components/organisms/deployments/sessions/tabs/activities/singleActivityInfo.tsx
- src/constants/index.ts
- src/constants/sessions.constants.ts
- src/locales/en/deployments/translation.json
- src/types/hooks/useEventListener.type.ts
https://linear.app/autokitteh/issue/UI-1506/load-all-activities
> feat(UI-1506): load all session activities

- src/components/organisms/deployments/sessions/activities-chart/executionFlowChart.tsx
- src/components/organisms/deployments/sessions/viewer.tsx
- src/constants/forms/formThemes.constants.ts
- src/locales/en/deployments/translation.json
https://linear.app/autokitteh/issue/UI-1529/accordion-title-execution-graph
> feat(UI-1529)(UI-1508): update execution flow

- src/components/organisms/chatbotIframe/chatbotIframe.tsx
> feat(UI-1512): add org id to chatbot url

- src/components/organisms/tour/custom-tours-steps/connections/oauthWaitStep.tsx
- src/components/organisms/tour/tourManager.tsx
- src/components/organisms/tour/tourPopover.tsx
- src/components/templates/appProvider.tsx
- src/constants/tour.constants.ts
- src/interfaces/components/tour.interface.ts
- src/interfaces/store/tour.interface.ts
- src/locales/en/tour/translation.json
- src/store/useTourStore.ts
- Remove the Skip Tour button
- Add a small close (X) icon in the top-right corner
- Add (green) buttons like in the first step for the remaining steps
https://linear.app/autokitteh/issue/UI-1491/improve-tour-popover
> feat(UI-1491)(UI-1533): enhance tour functionality with action buttons

- index.html
Replace Lucky Orange tool with Clarity: https://clarity.microsoft.com/
https://linear.app/autokitteh/issue/UI-1546/replace-lucky-orange-tool-with-clarity
> feat: replace lucky orange with clarity

- src/components/templates/descopeMiddleware.tsx
> feat: enhance manage search parameters and navigation after login

- src/constants/index.ts
- src/constants/project.constants.ts
- src/factories/fileOperations.ts
- src/hooks/useProjectActions.tsx
- src/utilities/templates.utils.ts
> fix(UI-1552): remove manifest file when creating from template

- src/enums/components/index.ts
- src/enums/components/readOnlyFile.enum.ts
> chore: remove redundant enum read-only file

- src/components/templates/appProvider.tsx
- src/utilities/processToursFromTemplates.utils.ts
Let me trace through what's happening with your input:
First call: currentPath="" encounters "walkthroughs" → recurses into it
Second call:  "walkthroughs", encounters "send_slack_message"
The bug: The code sees currentPath === toursDir (which is "walkthroughs" === "walkthroughs"), so it recurses AGAIN instead of processing "send_slack_message" as a tour
Third call: currentPath = "walkthroughs/send_slack_message, encounters files like "program.py" → but these are files, not directories, so they get skipped
The problem is that when we're at the walkthroughs level, the direct children (send_slack_message, quickstart, etc.) ARE the tours and should be processed as tours, not recursed into further.
https://linear.app/autokitteh/issue/UI-1562/fix-tour-templates-loader
> fix(UI-1562): fix tour templates loader

- src/components/templates/appProvider.tsx
Continuing @itayd 's comment from here: https://github.com/autokitteh/web-platform/pull/1214- removed redundant dependency.
https://linear.app/autokitteh/issue/UI-1562/fix-tour-templates-loader
> refactor(UI-1562): remove redundant dependency from templates fetch use-effect

- package-lock.json
> chore: update browsers-list-db

- src/api/grpc/transport.grpc.api.ts
- src/constants/namespaces.logger.constants.ts
- src/services/http.service.ts
If we get 429 status from gRPC or HTTP - display rate limit
https://linear.app/autokitteh/issue/UI-1540/if-we-get-429-status-from-grpc-or-http-display-rate-limit
> feat(UI-1540): check 429 status gRPC and HTTP

- src/components/organisms/tour/tourPopover.tsx
- src/interfaces/store/tour.interface.ts
- src/store/useTourStore.ts
Improve walkthrough tours
https://linear.app/autokitteh/issue/UI-1579/remove-redundant-functions-for-example-fetch-tours
https://linear.app/autokitteh/issue/UI-1580/remove-redundant-functions-for-example-fetch-tours
> refactor(UI-1579): improve walkthrough tours

- src/constants/global.constants.ts
- src/constants/index.ts
- src/services/sessions.service.ts
> refactor(UI-1635): increase session termination delay to 20s

- src/components/organisms/chatbotIframe/chatbotIframe.tsx
- src/services/iframeComm.service.ts
> fix communications issues between chat and webplatform  

- src/components/organisms/codeFixDiffEditorModal.tsx
- src/components/organisms/editorTabs.tsx
- src/interfaces/components/codeFixDiffEditor.interface.ts
> fix: remove logs from system log

- src/hooks/useChatbotIframe.ts
- src/locales/en/chatbot/translation.json
- src/locales/en/services/translation.json
- src/services/iframeComm.service.ts
- src/services/logger.service.ts
**Implements Retry Logic**: Added automatic retry mechanism (3 attempts with 2-second delays) for failed connections
**Better Error Handling**: Distinguishes between different error types and handles them appropriately  
**Timing Improvements**: Added 100ms delay before handshake initiation to ensure iframe is fully ready
**Enhanced Logging**: Added debug logging to track connection flow
The original implementation had several issues:
```typescript
// OLD: Single attempt, immediate failure
handleError("connectionError", "Timeout waiting for iframe connection");
// NEW: Retries with backoff
scheduleRetry("Connection timeout", retryCount, "connectionError", "...");
```
Iframe wasn't fully loaded when handshake was initiated. No timing buffer between iframe setup and communication attempts. …
> fix(UI-1709): fix timeout with chat in iframe

- src/locales/en/login/translation.json
> feat(UI-1757): new login content page

- src/components/organisms/settings/organization/billing/organizationBilling.tsx
- src/locales/en/billing/translation.json
> fix: tokens usage in billing

- src/app.tsx
- src/components/molecules/menu/menu.tsx
- src/components/organisms/ai.tsx
- src/components/organisms/index.ts
- src/components/organisms/topbar/dashboard.tsx
- src/components/organisms/welcome.tsx
- src/locales/en/dashboard/translation.json
- src/locales/en/global/translation.json
- Add new AiPage component with AI workflow creation interface
- Include interactive form for plain English workflow descriptions
- Add pre-defined workflow templates with quick-start buttons
- Integrate chatbot iframe modal for AI-assisted development
- Add routing and navigation support for /ai path
- Include comprehensive translations for AI page content
> feat: duplicate welcome page - to be able changing welcome page and ai separately

- .github/actions/setup-test-env/action.yml
- .github/workflows/build_test_and_release.yml
> ci: increase timeout to fix E2E tests

- .commitlintrc.json
- .github/pull_request_template.md
- CLAUDE.md
- release.config.mjs
This PR enhances the semantic-release configuration to be more flexible with commit message formats and ensures consistent releases for all meaningful changes.
**Key Changes:**
- Added flexible regex patterns to handle commit message variations (e.g., `fix (UI-1818):` vs `fix(UI-1818):`)
- Implemented catch-all rule to release patches for any commit that doesn't start with `docs`, `test`, or `ci`
- Maintains backward compatibility with existing conventional commit patterns
Previously, commits like `fix (UI-1818): clarity(#1325)` failed to trigger releases because semantic-release expected exact conventional commit format without spaces. This caused missed releases for valid bug fixes and features.
> fix: bump version for all commits msgs except docs, ci, test

- .github/workflows/build_test_and_release.yml
- release.config.mjs
Release commits with `[skip ci]` were being ignored by both GitHub Actions and Netlify, causing Netlify deployments to miss version bumps.
Replaced `[skip ci]` with `[skip actions]` which is GitHub Actions-specific:
- ✅ **GitHub Actions**: Skips CI for release commits (prevents infinite loops)
- ✅ **Netlify**: Deploys release commits normally (doesn't recognize `[skip actions]`)
- **release.config.mjs**: Updated semantic-release commit message from `[skip ci]` to `[skip actions]`
- **build_test_and_release.yml**: Added workflow condition to skip when `[skip actions]` is present
After the merge, verify:
1. Release commits trigger Netlify deployments
2. Release commits do not trigger GitHub Actions workflows
> fix: replace [skip ci] with [skip actions] to enable Netlify deployments

- .github/workflows/build_test_and_release.yml
- release.config.mjs
> fix: change skip actions label name
